### ISSUE TITLE
express-fileupload

### ISSUE THREAD

**Issue by sinchi** [richardgirges/express-fileupload#1]
Hello
i have an issue with express-fileupload  module when i upload the file , i receive a empty file with 0 octet !!

**Comment by richardgirges** [comment]
@sinchi can you provide steps on how I can reproduce this issue?

**Comment by richardgirges** [comment]
@sinchi still waiting on repro steps. Pushed a couple updates since then. Will close this out; lemme know if the issue still exists and I'll look into it.
