### ISSUE TITLE
multiple file upload feature or documentation

### ISSUE THREAD

**Issue by dantheman213** [richardgirges/express-fileupload#10]
This module doesn't appear to allow multiple file upload. Or if it does the documentation does not cover it.

**Comment by richardgirges** [comment]
Hi there,

The module does allow multiple file uploads - I'll update the documentation to cover this. 

If you were two upload two files (i.e. sampleFile1 and sampleFile2), they would both be accessible from:

`req.files.sampleFile1`

and

`req.files.sampleFile2`

**Comment by adjeiessel** [comment]
var thisFile;
    if (!req.files) {
        res.send('No files were uploaded.');
        return;
    }
    for (var key in req.files) {
        thisFile = req.files[key];
        console.log(req.files[key].name);
        thisFile.mv('public/images/' + req.files[key].name, function(err) {
        if (err) {
          console.log(err);
        }
        else {
           console.log('File uploaded!');
        }
    });

    }
I tried this and it works. Having 1 or more input type as file. But each input file had a different name and posted as enctype="multipart/form-data" works.
But a documentation would be very much appreciated because it is really had to get this clue since I need to read issue to see if some had a similar problem to get a clue.

**Comment by dantheman213** [comment]
thanks for the information and for also adding a task to write in documentation that covers multiple file upload.

**Comment by richardgirges** [comment]
[Release v0.0.6](https://github.com/richardgirges/express-fileupload/releases/tag/v0.0.6) is up. Better documentation as well. Hope things are going well with this package!

**Comment by adjeiessel** [comment]
Just read through the current documentation and it is very clear on how to work with this module . It goes straight to the point to describe the very use case senarios which is awesome . 
Good practical explanation

**Comment by bpiv400** [comment]
Hi, express-fileupload clearly supports multiple file upload when the files are coming from inputs with different names. But does the package support uploading multiple files from a single input tag with the multiple attribute? Something like this: 
`<input type="file" name="myPictures" multiple></input>`

**Comment by yagoml** [comment]
The same of @bpiv400. Need get multiple files for the same input

**Comment by shyamvir2506** [comment]
Hi @bpiv400 ,
this package is supporting uploading multiple files from a single input tag with the multiple attribute. Something like this:
`<input type="file" name="myPictures" multiple></input>`

You can upload files like below.

app.post('/', function(req, res){
    if(req.files){
        var file = req.files.filename;
        for(var i = 0 ; i < file.length; i++){
            file[i].mv('./upload/'+file[i].name, function(err){
                if(err){
                    res.send(err);
                }
            })
            
        }
        res.send('all files uploaded.');
    }
})

**Comment by mathewk2017** [comment]
Hi, @shyamvir2506 it is not working for me.can you log that file variable so that I can check where I went wrong

**Comment by shadab14meb346** [comment]
I tried and it is working for multiple files upload using for loop like req.files.uploadedfile.lenth is giving the number of the uploaded files, but when I am uploading only a single file then req.files.uploadedfile.lenth is coming as undefined and with this my for loop logic to upload file is not working in case of single upload.

**Comment by RomanBurunkov** [comment]
Hi @shadab14meb346 ,

If you upload single file, middleware adds an object, not an array so there is no 'length' parameter.
You need to check whether you got an array or just a single object.
