### ISSUE TITLE
Different way to enable it then app.use()?

### ISSUE THREAD

**Issue by cosminalco** [richardgirges/express-fileupload#103]
Can be enabled with the format bellow?

`import * as functions from 'firebase-functions'`
 `import * as fileUpload from 'express-fileupload'`
 `export const read = functions.https.onRequest(async (req, resp) => {`
     `if (req.method.toUpperCase() === 'POST') {`
          `// process the form here`
     ` }`
     `response.send('webpage')`
` })`

For functions.https.onReques:

> function onRequest(handler: (req: functions.Request, resp: functions.Response) => void): functions.HttpsFunction
Handle HTTP requests.
@param handler
A function that takes a request and response object, same signature as an Express app.

I know I can use `exports.main = functions.https.onRequest(app)` but just wondering, will save some time sometimes.

**Comment by richardgirges** [comment]
Hi @cosminalco, the only supported way to use express-fileupload right now is with `app.use`.

I suppose you could also try to chain it directly in a specific route, like so (beware this isn't officially supported):
```javascript
app.get('/foo', fileUpload(), (req, res) => {
  // do stuff
});
```
