### ISSUE TITLE
Looking for some help.

### ISSUE THREAD

**Issue by ThatTonybo** [richardgirges/express-fileupload#104]
I'm making my own forum app and decided to use this over my own custom implementation for uploading avatars and attachments.

More specifically, I have no idea how to do these two things:
- Add an upload form itself to the users settings page.
- Turn the uploaded image into content that the HTML `<img>` can accept (I store avatars in the database, hashed).

Some help on doing these would be appreciated; I'm using the latest express off npm and bcrypt for hashing.

Thanks in advance! 😄

**Comment by richardgirges** [comment]
Hi @ThatTonybo take a look at the example folder here: https://github.com/richardgirges/express-fileupload/tree/master/example
