### ISSUE TITLE
latest  library when uploading 3gb file crashes the library

### ISSUE THREAD

**Issue by geetee24** [richardgirges/express-fileupload#106]
if one tries to upload a 3gb file, the library crashes.  any suggestions on how to solve this?

**Comment by ksfreitas** [comment]
Take a look in my fork: https://github.com/ksfreitas/codebit-express-fileupload/blob/master/README.md#codebit-express-fileupload

**Comment by richardgirges** [comment]
This is resolved by PR #109 - you can now use temp file uploads instead of uploading directly to memory.
