### ISSUE TITLE
Path to temp files.

### ISSUE THREAD

**Issue by RomanBurunkov** [richardgirges/express-fileupload#114]
According to the documentation it is possible to set path to store temporary files when useTempFiles set to true.

> Using useTempFile Options
> Use temp files instead of memory for managing the upload process. Please note: md5 hashes will not be generated when using tempFiles
> 
> app.use(fileUpload({
>     useTempFiles : true,
>     tempFileDir : '/tmp/'
> }));

I've set tempFileDir : '/tmp/', so middleware should save files to the '/tmp/' folder.
But it saves it to the 'tmp' folder in the folder for the middlewhare module, mean '/app/node-modules/express-fileupload/tmp/'.

Is that correct or it saves files in the both folders or there are some errors in documentation?

**Comment by RomanBurunkov** [comment]
It looks like I got some old code from npm, cause I see that I have

  const dir = __dirname + (options.tempFileDir || '/tmp/');

insted of

  const dir = options.tempFileDir || process.cwd() + '/tmp/';

Which persist in a git repository.

**Comment by yianni-ververis** [comment]
try './tmp/

**Comment by RomanBurunkov** [comment]
Hii @yianni-ververis , this issue was fixed it the last alpha.
