### ISSUE TITLE
Note: request.files undefined

### ISSUE THREAD

**Issue by adamasantares** [richardgirges/express-fileupload#117]
If anyone will get this issue even they have no mistakes with encType.
I got problem of undefined just because I've inserted ```app.use(fileUpload());``` after another app.use(),
so just know that it must be inserted by this way:

```
const app = new Express();
app.use(fileUpload()); <-- exactly after new Express() !
```

**Comment by SunilJamkatel** [comment]
Still showing undefined on mine, any fixes?

**Comment by RomanBurunkov** [comment]
For me this question in not about this module.
It is about how to use middleware in Express...

**Comment by richardgirges** [comment]
@adamasantares I don't think I understand the question. Can you tell me what middlewares you're loading before expressFileupload() that may be causing issues?

**Comment by below-1** [comment]
Ensure you includes "Content-Type: multipart/form-data" in your header. Specially when using Postman
