### ISSUE TITLE
[question] File upload without `useTempFile` results in empty files

### ISSUE THREAD

**Issue by kittaakos** [richardgirges/express-fileupload#118]
My files are created but the content is empty after calling `mv` on the `UploadedFile`. I am using `"express-fileupload": "^1.1.1-alpha.2"`.

```js
// @ts-check

const fs = require('fs');
const temp = require('temp');
const path = require('path');
const express = require('express');
const fileupload = require('express-fileupload');

const track = temp.track();
const uploadRoot = track.mkdirSync();

const port = process.argv[2] || 8080;
const app = express();
app.use(fileupload());

app.post('/upload', (req, res) => {
    if (!req.files) {
        return res.status(400).send(`No 'files' were selected for upload.`);
    }
    const keys = Object.keys(req.files);
    if (keys.length === 0) {
        return res.status(400).send(`No 'files' were selected for upload.`);
    }
    for (const key of keys) {
        const files = req.files[key];
        const uploads = Array.isArray(files) ? files : [files];
        for (const upload of uploads) {
            const { name } = upload;
            const toPath = path.join(uploadRoot, name);
            upload.mv(toPath, error => {
                if (error) {
                    return res.status(500).send(`Failed to upload ${name}.`);
                }
                console.log(`File ${fs.existsSync(toPath) ? 'exists' : 'does NOT exist'} under ${toPath}.`);
                if (fs.existsSync(toPath)) {
                    console.log(`Content of ${toPath}:`);
                    console.log(fs.readFileSync(toPath).toString());
                }
            });
        }
    }
    res.status(200).send();
});

app.listen(port, () => {
    console.log(`Server is listening on ${port}...`);
    console.log(`Upload functionality is rooted to ${uploadRoot}`);
});
```

The files I am trying to upload.
```bash
$ pwd && echo foo > foo.txt && echo bar > bar.txt && cat foo.txt && cat bar.txt
/Users/akos.kitta/Desktop
foo
bar
$ curl -F 'foo.txt=@/Users/akos.kitta/Desktop/foo.txt' -F 'bar.txt=@/Users/akos.kitta/Desktop/bar.txt' http://localhost:8080/upload
```

The buffer-based move logic never runs because the [`!options.tempFilePath` is `false`](https://github.com/richardgirges/express-fileupload/blob/f9d7bbd792523ea40570d20123f431c8ba70070d/lib/fileFactory.js#L20) although I set neither the `useTempFiles` nor the `tempFileDir` properties in the options. Perhaps [this change](https://github.com/richardgirges/express-fileupload/commit/1a201332fe8106175ed6b9564a2810859d264150#diff-8f22e40961e92410bc58db6fb980b3f0R20) is related. If in debug mode, I explicitly unset the `options.tempFilePath` and the [`moveFromBuffer`](https://github.com/richardgirges/express-fileupload/blob/f9d7bbd792523ea40570d20123f431c8ba70070d/lib/fileFactory.js#L77) is called, then it works as expected.

Thank you!

**Comment by RomanBurunkov** [comment]
Looks you are right.

this tempFilePath allways has a value, probably it is a not best way for such check.

I'm currently working on some changes for this module and they also will fix this issue.

**Comment by kittaakos** [comment]
> I'm currently working on some changes for this module and they also will fix this issue.

Awesome. ❤️ Let me know if there's anything I can assist you.

As a workaround, I did this for now:
```js
const { name, data } = upload;
const toPath = path.join(uploadRoot, name);
upload.mv(toPath, uploadErr => {
    if (uploadErr) {
        return res.status(500).send(`Failed to upload ${name}.`);
    }
    const stream = fs.createWriteStream(toPath, { encoding: 'utf8' });
    stream.once('open', () => {
        stream.write(data, writeErr => {
            if (writeErr) {
                return res.status(500).send(`Failed to upload ${name}.`);
            }
            stream.close();
            console.log(`File ${fs.existsSync(toPath) ? 'exists' : 'does NOT exist'} under ${toPath}.`);
            if (fs.existsSync(toPath)) {
                console.log(`Content of ${toPath}:`);
                console.log(fs.readFileSync(toPath).toString());
            }
        })
    });
});
```

**Comment by RomanBurunkov** [comment]
Hi, @kittaakos , @richardgirges 

I've created some changes which will fix that issue. please see PR #119

**Comment by kittaakos** [comment]
@RomanBurunkov, I have checked out the [`master` of your fork](https://github.com/RomanBurunkov/express-fileupload/tree/master); unfortunately, I had test failures. I am more than happy to verify your changes once more when the build is fixed.

**Comment by RomanBurunkov** [comment]
@kittaakos Fixed some typos and erros. All tests passed ;)

**Comment by kittaakos** [comment]
> All tests passed ;)

Nice. I can confirm, my example from above works with your changes 🎉

**Comment by richardgirges** [comment]
v1.1.1-alpha.3 released on NPM: https://github.com/richardgirges/express-fileupload/releases/tag/v1.1.1-alpha.3
