### ISSUE TITLE
Name of uploaded file

### ISSUE THREAD

**Issue by Abhimanyu310** [richardgirges/express-fileupload#12]
How do we get the name of the uploaded file? There is no documentation about it

**Comment by richardgirges** [comment]
Hi @Abhimanyu310  I will start working on documentation for this - the filename should be accessible from the file object. For instance, if your input name was `uploadImage` and the file name you uploaded was `foo.jpg` you would access it from:

`req.files.uploadImage.name // foo.jpg`

**Comment by Abhimanyu310** [comment]
@richardgirges Thanks, that worked.

**Comment by richardgirges** [comment]
[Release v0.0.6](https://github.com/richardgirges/express-fileupload/releases/tag/v0.0.6) is now up. Better documentation in the README. Hope things are going well with this package.
