### ISSUE TITLE
Cannot pass in .mv() function

### ISSUE THREAD

**Issue by dlazzy** [richardgirges/express-fileupload#121]
Hello,

I'm reopening this issue because I think I forgot something to pass in **.mv()** function. Everything works, but the http POST stuck pending because nothing is returned. Here the `console.log('here')` is never shown in console :

```js
router.post('/upload/img', (req, res) => {
  if (Object.keys(req.files).length == 0) {
    return res.status(400).send('No files were uploaded.');
  }
  let file = req.files.upload_file;

  file.mv(__dirname + '/../../public/imgs/articles/' + file.name), (err) => {
    if (err)
      return res.status(500).send(err);

    res.send('File uploaded!');
  };
});
```

Even with the output produced by the **morgan** package I don't see the call, but the file is created in the right folder :thinking: Thanks for you help

**Comment by RomanBurunkov** [comment]
Do you use useTempFiles option or upload files into a memory?

**Comment by dlazzy** [comment]
This is the config I use :

```js
app.use(fileUpload({
  preserveExtension: true,
  useTempFiles: false
}));
```

What do you mean by 'lates' ? Currently this is the version I use : `"express-fileupload": "^1.1.1-alpha.2"`

Thanks

**Comment by RomanBurunkov** [comment]
Hi @dlazzy ,

I meant 'latest', sorry for typo.
Currently it is '1.1.1-alpha.3' and there are some fixes for mv method in it.

**Comment by dlazzy** [comment]
Thanks for your answer, so I updated to **alpha.3** but it's not working :confused: 

Here is my code :

```js
if (Object.keys(req.files).length !== 0) {
  file = req.files.img;

  file.mv(__dirname + '/../../public/imgs/ads/' + id + '-' + file.name), (err) => {
    console.log('here');
    if (err)
      return res.status(500).send(err);
  };
}
```

And the `console.log('here');` is not shown in logs.
Maybe because **express-fileupload** is done in my server.js and then used in imported Routes ?

I mean :

```js
// server.js
const fileUpload = require('express-fileupload');

const adsRoutes = require('./routes/dashboard/ads');
// other express, app config

app.use('/dashboard/ads', adsRoutes);
```

```js
// ads.js (routes)
/* POST handle ad edition */
router.post('/edit/:id', (req, res) => {
    let id = uniqid();

    if (Object.keys(req.files).length !== 0) {
        let file = req.files.img;

        file.mv(__dirname + '/../../public/imgs/ads/' + id + '-' + file.name), (err) => {
            if (err)
            return res.status(500).send(err);
        };
    }

    // ...
});
```

**Comment by RomanBurunkov** [comment]
Hm...it looks fstream from fileFactory.js doesn't emmit 'close' event.

Line 89:

        fstream.on('close', function() {
          successFunc();
        });

**Comment by dlazzy** [comment]
So it mean that a module issue ? :confused:

**Comment by RomanBurunkov** [comment]
@dlazzy , probably so.

Try to change 'close' to 'finish' in your local fileFactory.js at line 89 and test it again ;)

**Comment by dlazzy** [comment]
This has no effect, I double tried but no changes. For other purpose I need to use Node 7.8.0, this can be a problem ?

**Comment by RomanBurunkov** [comment]
Well, currently I don't have any ideas what else can be wrong....but you can try to use useTempFiles: true, as a temporary solution.

**Comment by dlazzy** [comment]
Yeah no problem I'll do this ;) And closing the issue, it's not a big bug, for me !
