### ISSUE TITLE
mv does not work accross filesystems

### ISSUE THREAD

**Issue by pdumais** [richardgirges/express-fileupload#125]
If using a temp path and doing mv() across filesystems, we get an error "EXDEV: cross-device link not permitted"

I believe this is due to the underlying call to rename()

**Comment by RomanBurunkov** [comment]
Yeap, looks it need to be changed to use based on streams copy + unlink instead of rename.

**Comment by RomanBurunkov** [comment]
I've fixed this issue in my local version and going to add that fix with a next PR if @richardgirges will have a chance to review and publish the current one.

**Comment by richardgirges** [comment]
@RomanBurunkov I've created a new release with your merged PR: https://github.com/richardgirges/express-fileupload/releases/tag/v1.1.2-alpha.1

Feel free to update the release notes and close any issues that you've resolved. 

(I still need to give you npm publish access, haven't forgotten)

**Comment by RomanBurunkov** [comment]
That was fixed in 1.1.3-alpha1
