### ISSUE TITLE
bug in filename tmp multi file conflict with same name and time

### ISSUE THREAD

**Issue by sistemasnegros** [richardgirges/express-fileupload#129]
**bug in filename tmp multi file conflict with same name and time.
File tempFileHandler.js**

`const fs = require('fs');
const path = require('path');

module.exports = function(options, fieldname, filename) {
  const dir = path.normalize(options.tempFileDir || process.cwd() + '/tmp/');

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir);
  }
  let tempFilePath = path.join(dir, 'tmp' + Date.now());
  let writeStream = fs.createWriteStream(tempFilePath);
  let fileSize = 0; // eslint-disable-line
`

change for > solved

`module.exports = function(options, fieldname, filename) {
  const dir = path.normalize(options.tempFileDir || process.cwd() + '/tmp/');

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir);
  }
  **let tempFilePath = path.join(dir, 'tmp' + filename + Date.now());**
  let writeStream = fs.createWriteStream(tempFilePath);
  let fileSize = 0; // eslint-disable-line`

**Comment by RomanBurunkov** [comment]
Hi, @sistemasnegros 

I also mentioned that such naming could lead to problems.
Have you faced this issue?

Also I don't think with this a good idea to use filename, because it could be unsafe.

I have several ideas about that:

- Use processed filename, like it done with option safeFileNames.
- Add some random number to the file name.
- Use uuid v4 for naming.

**Comment by RomanBurunkov** [comment]
Probably we can add something like that to the utilities module and use this function to generate more unique file names:

`//Parameters which used to generate unique temporary file names
const TEMP_COUNTER_MAX = 65536;
const TEMP_PREFIX = 'tmp';
let tempCounter = 1;

/**
 * Generates uniq file name.
 */
const getTempFilename = (prefix) => {
  prefix = prefix || TEMP_PREFIX;
  tempCounter ++;
  if(tempCounter > TEMP_COUNTER_MAX) tempCounter = 1;
  return `${prefix}_${tempCounter}_${Date.now()}`;
};`

**Comment by sistemasnegros** [comment]
thanks! you solution!
but solved my problem the cuncurrense in mutiple file.
[https://www.npmjs.com/package/short-id](https://www.npmjs.com/package/short-id)

`let tempFilePath = path.join(dir, 'tmp' + filename + shortid.generate() + Date.now());`

**Comment by RomanBurunkov** [comment]
That should be fixed with PR #130.
