### ISSUE TITLE
Callback on abort?

### ISSUE THREAD

**Issue by crizant** [richardgirges/express-fileupload#138]
Hi, is it possible to add a `onAbort` callback like:

```
{
  onAbort: (req, res) => {

  }
}
```

So that I can do custom actions, e.g. throw an error, or return a JSON response on abort?

**Comment by RomanBurunkov** [comment]
Hi, that feature will be available in next release.

In a meantime you can try 'responseOnLimit' option, just set it to your stringified JSON response.

**Comment by crizant** [comment]
but under the hood the content type will not be `application/json` :(

btw i have another request, is it possible to set the list of allowed mime-types, or just `image/*`?

**Comment by RomanBurunkov** [comment]
I see...but that can work as a temporary workaround.

According your secont question.

I'm also working on aditional onFileHandler which will provide you an ability to apply some filters before uploading process started and cancel it if e.g. mime type doesn't match.

**Comment by RomanBurunkov** [comment]
User defined limit handler now can be added via limitHandler option.
