### ISSUE TITLE
Empty buffer data?

### ISSUE THREAD

**Issue by crizant** [richardgirges/express-fileupload#139]
Here is my settings:

```
{
    useTempFiles: true,
    abortOnLimit: true,
    limits: {
      fileSize: 10 * 1024 * 1024 // 10 MB
    }
  }
```

then I read the file in `req` object:
```
const { image } = req.files
console.log(image.size) // 103984
console.log(image.data.length) // 0
```

The result is `0`.

**Comment by RomanBurunkov** [comment]
I don't see any issues in that.

You can get file data only in case of in memory upload(useTempFiles: false).

**Comment by crizant** [comment]
Oh, please state this behavior in the documentation.

BTW if I want to use `useTempFiles: true` and get the buffer, I need to use `fs.readFileSync(image.tempFilePath)`?

I think the library should provide a handy function to do it.

**Comment by RomanBurunkov** [comment]
That leads to the issues with performance or memory in case of large files.

E.g reading in to the RAM 3Gb size file for sure will cause out of memory issue.

This module just provides you ability to chose where to store uploaded data: in to the RAM or to a temporary file and if you chose RAM it provides a buffer with file data.

But you should use memory for upload or reading huge files into it really cautiously.

**Comment by RomanBurunkov** [comment]
This was documented.

**Comment by melitus** [comment]
@RomanBurunkov But I tried setting the `useTempFiles: true` and passing the tempFIlePath to my google cloud storage functions it did not work. I got this when an image is saved - https://storage.googleapis.com/temp-hold-eu/Z0cuwDoD6-Screenshot%25202022-08-05%2520at%252017.21.28.png. This is my code shown below

```
const uploadToGCS = async (
  file: Buffer,
  fileName: string,
  mimeType: string,
): Promise<string> => {
  const storage = new Storage({
    keyFilename: config.googleBucket.serviceKeyPath,
  });
  const bucket = storage.bucket(config.googleBucket.publicBucket);
  const gcsFileName = `${Date.now()}-${fileName}`;
  // Create a new blob in the bucket and upload the file data.
  const fileToUpload = bucket.file(gcsFileName);
  const fileStream = fileToUpload.createWriteStream({
    metadata: {
      contentType: mimeType,
    },
    resumable: false,
  });
  return new Promise((resolve, reject) => {
    fileStream.on('finish', () => {
      const publicUrl = getPublicUrl(encodeURIComponent(fileToUpload.name));
      fileToUpload
        .makePublic()
        .then(() => resolve(publicUrl))
        .catch(reject);
    });
    fileStream.on('error', (ex) => {
      Logger.log(ex, 'GCS');
      return reject;
    });
    fileStream.end(Buffer.from(file, ));
  });
};
```
