### ISSUE TITLE
uploaded_file.mv() is overridden by cleanDir

### ISSUE THREAD

**Issue by jeanmarie-dormoy** [richardgirges/express-fileupload#141]
Sorry, I have an issue:

I call cleanDir before mv.

cleanDir is a personal function which deletes all files in the directory where uploaded_file will be stored. But somehow, I guess that uploaded_file.mv() is faster than cleanDir.

If i do two successive POST requests in postman, the first post will upload the file to the right directory, but the second post will delete it instead of deleting it + uploading it again. 
The weird thing is that the POST request works if there is no file, fails if there is a file to delete in the given directory (cleanDir must be too slow compared to mv, so my new file may be successfully uploaded but deleted just after by cleanDir).

How can I make this work? I tried using promises and async await without success. As you can see in the node console screenshot, I don't have any errors.

thanks in advance, any help would be greatly appreciated
![image](https://user-images.githubusercontent.com/43047853/56082505-c68f8a80-5e19-11e9-9cd8-b5a5678b38ca.png)
![image](https://user-images.githubusercontent.com/43047853/56082535-3bfb5b00-5e1a-11e9-9bd1-e6f1a2f2f862.png)
![image](https://user-images.githubusercontent.com/43047853/56082547-546b7580-5e1a-11e9-8605-74fb0a73a8e3.png)
![image](https://user-images.githubusercontent.com/43047853/56082673-db6d1d80-5e1b-11e9-8555-6f1948f028d3.png)

**Comment by RomanBurunkov** [comment]
Clearing folder while multiple uploads sounds crazy for me.

**Comment by jeanmarie-dormoy** [comment]
I don't do multiple uploads while clearing folder. I just want to clear contents of folder and then upload the file to that folder. It is for a project and we need to delete old version of the file before uploading the newest version, so no, it is not that crazy.

**Comment by RomanBurunkov** [comment]
I see, but I bet you do ;) Any way, probably deleting only uploaded file, instead of clearing whole folder will do the job ?

**Comment by RomanBurunkov** [comment]
One thing I noticed in the code above that mv file method is calling with await and also a callback.
In case you pass a callback to mv it doesn't return a promise.

Closing since it's not a module issue.
