### ISSUE TITLE
I have used apostrophe in filename then it is replaced by %22, Any method to preserve filename?

### ISSUE THREAD

**Issue by rajatsehgal2010** [richardgirges/express-fileupload#144]

**Comment by RomanBurunkov** [comment]
Hi, could you clarify the following:

1. Do you use useTempFiles option.
2. Do you use mv method.
3. Do you see name with %22 in the 'file' object or it appears on the filesystem?

Your code examples also could be helpfull.

**Comment by RomanBurunkov** [comment]
Also you can use 'safeFileNames' or module like urldecode to parse file name.

**Comment by rajatsehgal2010** [comment]
I have used mv method, and it appears on the filesystem.

**Comment by RomanBurunkov** [comment]
Hi @rajatsehgal2010 ,

I've added option for this issue: uriDecodeFileNames, see readme doc.
