### ISSUE TITLE
is it safe to overwrite the buffer with another buffer?

### ISSUE THREAD

**Issue by r3wt** [richardgirges/express-fileupload#145]
looking at the source, it looks like it should be safe. the reason i want to do it, is because i need to resize the image, but then i want to use the `mv()` function to move it after i resize it. it should work right?

**Comment by RomanBurunkov** [comment]
Hi, 
I reckon that should be ok, but I would recommend using useTempfiles: true and process temporary file and then move it.

In memory upload can be dangerous in case of huge uploaded files size.
