### ISSUE TITLE
How to clean up temporary files when the user cancels the transfer before the end?

### ISSUE THREAD

**Issue by wbulot** [richardgirges/express-fileupload#148]
Do I have a way to delete temporary files in case the user's upload does not succeed?
My application handles a lot of uploads and the fact that I can't clean up temporary files is a big problem.
I could do a recurring task but I have no way to dissociate the temporary zombie files from those currently in use.

Any ideas ?

Thank you

**Comment by r3wt** [comment]
you could have a process run periodically that:

1. reads the tmp dir using `fs.readDir()`
2. iterate over the files returned, and make a call to `fs.fstat()` for each.
3. check to see if the `atime` of the file returned from `fs.fstat()` is older than 1 hour (assuming no file upload could still be processing after an hour), and if so delte the file.

**Comment by RomanBurunkov** [comment]
Hi, 

Can you clarify steps how to reproduce this issue and show your code examples?

**Comment by RomanBurunkov** [comment]
This middleware built on busboy, and as far as I can see busboy doesn't handle connection abort from the client side.

Probably request close event can help to deal with such cases.

**Comment by wbulot** [comment]
How can I use the "close" event in my case?
Would I be able to retrieve the path of the previously used tmp file to clean it ?

This is my test code using tmp files : 
```
var cors = require('cors')
var express = require('express')
var fileUpload = require('express-fileupload')

var app = express()

app.use(cors())
app.use(fileUpload({
    safeFileNames : true,
    preserveExtension: 10,
    useTempFiles: true,
    tempFileDir: "/tmp/"
}))
app.use(express.urlencoded({ extended: true }))

app.post('/upload', function(req, res) {
  console.log("upload called by "+req.headers['x-real-ip'])

  if(req.files)
  {
    var filesUploaded = req.files.filesUploaded;
    var filesToUpload = []
    if(Array.isArray(filesUploaded) == false)//One file to upload
    {
      filesToUpload.push(filesUploaded)
    }
    else //Multiple files to upload
    {
      filesToUpload = filesUploaded
    }

    for(var i = 0 ; i < filesToUpload.length; i++)
    {
      console.log(filesToUpload[i].name)
      console.log(filesToUpload[i].size)
      filesToUpload[i].mv("/tmp/"+filesToUpload[i].name, function(err)
      {

      })
    }

    console.log("upload finished by "+req.headers['x-real-ip'])
    res.send("ok")
  }
  else {
    res.send("nok")
  }
})

console.log("Server started")
app.listen(3000)

```

**Comment by RomanBurunkov** [comment]
Well probably request close event is not very good idea since it also doesn't fire in some cases.

One thought I have is to add a timeout, e.g 60 seconds and sets it every time when got file data and also clear it if got file's finish event.

If haven't got data during 60 seconds, cancel upload and clear all saved before data.

**Comment by r3wt** [comment]
@wbulot 

Here is what i am using. Its a scheduled job that runs every day at 1am similar to how cronjobs work.

```js
const schedule = require('node-schedule');
const fs = require('fs');

const tmpDir = '/tmp';

//every day at 1am we clean the temp files
const cleanUpSchedule = '0 1 * * *';
schedule.scheduleJob(cleanUpSchedule,function(){
    console.log('running job: clean up tmp files')
    fs.readdir(tmpDir,{withFileTypes:true},(err,files)=>{
        if(err){
            console.warn('unable to read temp files directory');
            console.log(err);
            return;
        }
        if(Array.isArray(files)){
            const time = (new Date()).getTime();//get ms since epoch
            //because of withFileTypes option, files are fs.Dirent objects instead of just string filenames.
            files.forEach(file=>{
                //make sure its a file before proceeding
                if(file.isFile()){
                    fs.stat(tmpDir+file.name,(err,stats)=>{
                        if(err){
                            console.warn('unable to fs.stat() file %s',file.name);
							console.log(err);
                            return;
                        }
                        //if the time the file created is greater than or equal to 1 hour, delete it
                        if(stats.birthtimeMs - time >= 3.6e+6) {
                            console.log('removing temp file %s',file.name)
                            fs.unlink(tmpDir+file.name,err=>{
                                if(err){
                                    console.warn('unable to remove temp file %s',file.name)
                                }else{
                                    console.log('temp file %s removed',file.name);
                                }
                            })
                        }else{
                            console.log('the temp file %s will not be removed due to not being old enough.',file.name);
                        }
                    })
                }
            })
        }
    })
});
```

**Comment by fatchan** [comment]
@wbulot How about this?

To remove temp files in a failure case:
```js
const remove = require('fs-extra').remove;
//could use standard fs if you prefer, i believe the method is called 'unlink'

module.exports = (req) => {
    if (req.files != null) {
        let files = [];
        const keys = Object.keys(req.files);
        for (let i = 0; i < keys.length; i++) {
            const val = req.files[keys[i]];
            if (Array.isArray(val)) {
                files = files.concat(val);
            } else {
                files.push(val);
            }
        }
        return Promise.all(files.map(async file => {
            remove(file.tempFilePath);
        }));
    }
}
```
Should handle deleting the temp files with a few advantages:
1. Removes temp files for all files in req.files, not just the ones you expect. Currently an uploaded file can come under any name in the form and it will be saved as a temp file. I dont think there is a busboy option for this. You can limit the _number_ of files or fields, but not limit the names.
2. Handles `multiple` input file uploads where `req.files.<something>` is an array of file objects.
3. Doesn't rely on scheduled/interval deletes and having to do more IO in listing files and checking dates.

I do this in all failure cases and inside my error handler in express, and havent any problems with stray temp files. I guess you could also use a try/catch/finally block and put this inside the finally statement.

**Comment by wbulot** [comment]
Hi @fatchan 

Thank you for your answer but the code will never be executed in the specific case I describe.
Indeed, the code is only executed at the end of a successful transfer.
In the event that the user cancels a transfer in progress, no error is triggered and the code inside the /upload route is not executed.
I therefore have no way to handle a cancelled transfer except with workarounds like the various examples above.

Let me know if I missed something.

**Comment by fatchan** [comment]
No worries, this was just a musunderstanding. The body of the question does not exactly match the title. The question mentioned "user's upload does not succeed" whereas the title is about cancelling/aborting upload. My answer was to address failed uploads.

-----

OK I did some more messing around and came up with this:
In `lib/processMultipart.js` I made a few changes:
```js
module.exports = (options, req, res, next) => {
  req.files = null;

  const cleanups = [];
  req.on('aborted', () => {
    cleanups.forEach(cleanup => {
      cleanup();
    })
  });

...

  // Build req.files fields
  busboy.on('file', (fieldname, file, name, encoding, mime) => {
    // Decode file name if uriDecodeFileNames option set true.
    const filename = uriDecodeFileName(options, name);

    const {dataHandler, getFilePath, getFileSize, getHash, complete, cleanup} = options.useTempFiles
      ? tempFileHandler(options, fieldname, filename)
      : memHandler(options, fieldname, filename);

    cleanups.push(cleanup);
```
The `aborted` event listener will fire if the user cancels the upload part way through, and then cleanup for each one is called, similar to if the error event fires, deleting the temp file.
Not sure this is the right way to handle this, but seems to work. Let me know what you think.

**Comment by wbulot** [comment]
I would also like to point out that I have tried some methods proposed above, namely deleting temporary files with a regular check. It seems that this is not possible because the node process always has the tmp files open. fs.unlink will work but the OS will not free up the space (verifiable with the lsof +L1 command).

@fatchan Thank you for your answer.
It seems that what you're proposing would fix the problem. It's beyond my skills, I'll let you judge.

**Comment by r3wt** [comment]
@wbulot an update to my solution above, you are correct. fs.unlink doesn't release the file handles, so the OS never free's the diskspace. We are working around this by truncating the file before calling unlink, and it seems to do the trick. we also have a job to restart the app every 24 hours to release the open handles. hope it helps. i've updated my code above, but here's whats changed for brevity:

```js
fs.truncate(tmpDir+file.name,()=>{
    fs.unlink(tmpDir+file.name,err=>{
        if(err){
            log.warn('unable to remove temp file %s',file.name)
        }else{
            log.info('temp file %s removed',file.name);
        }
    });
})
```

**Comment by wbulot** [comment]
@r3wt That's exactly what I'm doing.
It solves the space problem, but in reality, the files are still there.
It's still a worthwhile workaround.

**Comment by RomanBurunkov** [comment]
Added PR for that issue #168

**Comment by RomanBurunkov** [comment]
New version 1.1.6-alpha.5 published.
It cleanup temporary files(close stream and delete a file) if there were no data during uploadTimeout(default is 60000 msec).
