### ISSUE TITLE
Can't upload file larger than ~3 GB

### ISSUE THREAD

**Issue by wbulot** [richardgirges/express-fileupload#149]
Hi Everyone,

I just notice that I was unable to upload a file larger than 2 or 3 GB.
I'm not sure about the precise limit because sometimes it works for the same file that is around 2GB, but it never works for files that are more than 3GB. My server has 20gb of RAM so I don't think it is a memory issue.

This is the error message : 

```
buffer.js:250
    throw new ERR_INVALID_OPT_VALUE.RangeError('size', size);
    ^
RangeError [ERR_INVALID_OPT_VALUE]: The value "3068874752" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:272:3)
    at Function.concat (buffer.js:452:25)
    at getBuffer (/usr/src/app/node_modules/express-fileupload/lib/memHandler.js:16:34)
    at FileStream.<anonymous> (/usr/src/app/node_modules/express-fileupload/lib/processMultipart.js:58:19)
    at FileStream.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1137:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

This is my test server.js : 

```
var cors = require('cors')
var express = require('express')
var fileUpload = require('express-fileupload')

var app = express()

app.use(cors())
app.use(fileUpload({
    safeFileNames : true,
    preserveExtension: 10,
    //useTempFiles: true,
    //tempFileDir: "/tmp/"
}))
app.use(express.urlencoded({ extended: true }))

app.post('/upload', function(req, res) {
  console.log("upload called by "+req.headers['x-real-ip'])

  if(req.files)
  {
    var filesUploaded = req.files.filesUploaded;
    var filesToUpload = []
    if(Array.isArray(filesUploaded) == false)//One file to upload
    {
      filesToUpload.push(filesUploaded)
    }
    else //Multiple files to upload
    {
      filesToUpload = filesUploaded
    }

    for(var i = 0 ; i < filesToUpload.length; i++)
    {
      console.log(filesToUpload[i].name)
      console.log(filesToUpload[i].size)
    }

    console.log("upload finished by "+req.headers['x-real-ip'])
    res.send("ok")
  }
  else {
    res.send("nok")
  }
})

console.log("Server started")
app.listen(3000)
```

**Comment by RomanBurunkov** [comment]
Files too large for in memory upload.
It looks there are some limitations in node's standard module buffer.

Do you have the same issue with useTempFiles: true?

**Comment by wbulot** [comment]
Indeed, seems like I don't have the issue with useTempFiles.
But I would like to use memory because of [Issue 148](https://github.com/richardgirges/express-fileupload/issues/148) and for performance reasons.
There is no way to avoid this "memory" problem ?

**Comment by RomanBurunkov** [comment]
I see.

My assumption that it is a node issue.
Buffer.concat not able to deal with a huge buffer arrays.

Which node version do you use?

**Comment by RomanBurunkov** [comment]
I've checked node docs and found out a node limitation for a single buffer size:

On 32-bit architectures, this value is (2^30)-1 (~1GB). On 64-bit architectures, this value is (2^31)-1 (~2GB).

This is why you are getting such errors for 'in memory' upload.

**Comment by wbulot** [comment]
It looks like this [article](https://airbrake.io/blog/nodejs-error-handling/err_buffer_too_large) refers to the same error.
It seems that the buffer.js constructor is [deprecated](https://github.com/nodejs/node/blob/master/lib/buffer.js#L149-L159) and that there is a new ways to manage this.
I'm not an expert at all and pretty new to nodejs thus I don't know if that would actually solve this problem.

**Comment by RomanBurunkov** [comment]
Not a module issue, for huge files only useTempFiles:true works.
