### ISSUE TITLE
req.files is null

### ISSUE THREAD

**Issue by Loxoz** [richardgirges/express-fileupload#154]
```js
const Express = require('express');
const app = Express();
const FileUpload = require('express-fileupload');
/* ... */
var httpport = 8080;

app.use(FileUpload({
    useTempFiles : true,
    tempFileDir : './tmp/'
}));

app.use((req, res, next) => {

    console.log(req.files); /* returns -> null (even with files) and not an empty object or object with the files */

    console.log(Object.keys(req.files).length);
    /* throw new Error:
     * TypeError: Cannot convert undefined or null to object
     * ...
     * at Busboy.busboy.on (.\node_modules\express-fileupload\lib\processMultipart.js:82:5)
     * at Busboy.emit (events.js:187:15)
     * at Busboy.emit (.\node_modules\busboy\lib\main.js:38:33)
     */
    /* Fix for the error, but still not able to get files: */
    console.log(Object.keys(req.files || {}).length); /* returns -> 0 */

    next();
});

app.listen(httpport, (err) => { /* ... */ });
```

**Comment by RomanBurunkov** [comment]
Don't see any issues from your description....
It looks there is no multipart data, so req.files is null.

**Comment by bigjoevtrj** [comment]
+1

same problem here.

**Comment by bigjoevtrj** [comment]
Problem found guys in my case,
If you're using fetch, you cannot use 'Content-Type' headers, it messes with boundary data, just use the FormData in post body and it works, fetch build the correct Content-Type to the request.

**Comment by eddex** [comment]
Here's an example that worked for me
```html
<input type="file" id="filePicker"></input>
```

```JavaScript
const input = document.getElementById('filePicker')
const file = input.files[0]
const formData = new FormData()
formData.append(input.id, file)
const response = await fetch('http://localhost:3001/upload', {
   method: 'POST',
   headers: {},
   body: formData
})
```

**Comment by amitlemosys** [comment]
Thank you It worked for 

> Here's an example that worked for me
> 
> ```
> <input type="file" id="filePicker"></input>
> ```
> 
> ```js
> const input = document.getElementById('filePicker')
> const file = input.files[0]
> const formData = new FormData()
> formData.append(input.id, file)
> const response = await fetch('http://localhost:3001/upload', {
>    method: 'POST',
>    headers: {},
>    body: formData
> })
> ```

Thank you!! it worked for me.
