### ISSUE TITLE
bugs for limitHandler and Number of file you can upload

### ISSUE THREAD

**Issue by Truth1984** [richardgirges/express-fileupload#155]
So basically there are two bugs.
1. If I set `useTempFiles: true`
I want to remove the file after I hit the limit, and i will use 
```
limitHandler: (req, res) => {
    // get the tempFilePath from req.files & remove the file from the disk
}
```
However, in this case, `req.files == null`, thus the file will remain on your disk then if I keep spamming, it will take all the space of your disk and crush the server.

2 I can't find anywhere to limit the amount of files of your uploads.
Thus, If I set `fileSize limit` to 100MB,
Even though you can write the proper code to check if `truncated == true`, and delete the file, but it happened after the user finish uploading right,
or use `abortOnLimit: true` then the tempfile will be kept on your server ...
I can upload few big chunks of files with few different computers from different ips, take over your disk and crush your server ?

**Comment by RomanBurunkov** [comment]
Invoking cleanup function in limit handler should help in case of 

> abortOnLimit: true

It can be added in to the processMultipart.js before  lines 46, 50.

**Comment by Truth1984** [comment]
And maybe add `ext` for file Obj ? so it's easy to check ext with mimetype and use mv() ?

**Comment by RomanBurunkov** [comment]
I didn't catch your update about ext.
Can you ellaborate it.

**Comment by Truth1984** [comment]
example:
```
{
name: 'flower.png',
data: <Buffer >,
size: '10240',
ext:'png'
}
```
I can upload multiple files with different mimetype in a form right,
so it's easy to use `mv()`
as `mv(path.resolve(dir, yourDesiredFilename+ext))`

**Comment by RomanBurunkov** [comment]
I see, but probably it should be a separate issue.

Still thinking about how to resolve cleanup and limits issue.

**Comment by RomanBurunkov** [comment]
Hi @Truth1984 ,

I've published 1.1.6-alpha.1 version, where I've added cleanup function if upload was aborted because of file size limit.

**Comment by RomanBurunkov** [comment]
In 1.1.6-alpha.5  there is also new timeout check added for incoming data.
If no data comes during dataTimeout(default is 60000 msec ), middleware invokes cleanup method which close temp file stream and then delete temp file.

**Comment by RomanBurunkov** [comment]
Fixed:

1. Upload timeout added
2. Cleanup temp files if limit reached.
