### ISSUE TITLE
Property 'mv' does not exist on type.

### ISSUE THREAD

**Issue by ld7ca** [richardgirges/express-fileupload#156]
Hi,
I'm new to express-fileupload and facing a problem with .mv()...

Some code:
```
import express = require('express');
const srv = express();
srv.use(require("body-parser").urlencoded({ extended: false }));
srv.use(require("body-parser").json());
srv.use(require('express-fileupload')());

srv.post('/api/users/:id/image', (req: express.Request, res: express.Response) => {

    let f = req.files.file;
    f.mv('/');

    res.end();
})
```

`mv()` is marked in my editor with this error: `Property 'mv' does not exist on type 'UploadedFile[]'.ts(2339)`

Types are installed. name, encoding, size etc. aren't available too. What am I doing wrong?

Greetings and many thanks,
Lukas

**Comment by ld7ca** [comment]
I can 'fix' this by removing `UploadedFile[]` from the index.d.ts. But what is the real solution?

**Comment by rip32700** [comment]
Same issue here.

**Comment by RomanBurunkov** [comment]
I'm not familar with TS, but that doesn't look like this module issue, probably You're getting this error because there's no type definition for the mv property. You should add the type definitions for the middleware to add mv to the file object.

**Comment by Relaxe111** [comment]
this file from:
`let f = req.files.file;`
 files is of type FileArray and can return a UploadedFile or UploadedFile []. since mv is present only on UploadedFile interface it can be seen in union of UploadedFile|UploadedFile[]. to solve this issue i just explicitly  declared file as UploadedFile like  so:
`let f = req.files.file as UploadedFile` and problem was solved. 
Hope it will help someone)

**Comment by Goldtek** [comment]
> Filed file from files is of type UploadedFile|UploadedFIle[]:
> `let f = req.files.file;`
> Since mv is present only on UploadedFile interface it can't be seen in union of UploadedFile|UploadedFile[]. to solve this issue I just explicitly declared file as UploadedFile like so:
> `let f = req.files.file as UploadedFile` and problem was solved.
> Hope it will help someone)

this works but what now happens in production

**Comment by Sparks1998** [comment]
I know I am late but hope some one find this usefull...

If you are 100% sure you are only uploading 1 file at a time then you can simply do: 

`let avatar = req.file.avatar as fileUpload.UploadedFile`

This interface contains everything you need else if you want several files so you can do:

`let avatars = req.files.avatars as fileUpload.UploadedFile[]`

This will be an array of files
