### ISSUE TITLE
mv slow,  always uses copyFile, even if fs.rename is possible

### ISSUE THREAD

**Issue by anneb** [richardgirges/express-fileupload#158]
After uploading a large file (using tempfiles), the mv function may take quite some time, because the tempfile is being copied instead of being renamed. This takes more time and requires more available disk space.

Pull request https://github.com/richardgirges/express-fileupload/pull/157 tries to rename the file and resort to copyFile only if the rename should fail.

**Comment by RomanBurunkov** [comment]
Hi @anneb , from the best of my knowledge that was changed from move to copy because mv method doesn't work if you try to mv file between different partitions.

Does your change work for such cases?

**Comment by anneb** [comment]
Indeed, the standard rename method does not work across partitions. For this reason, the code in the pull request first tries a rename and resorts to 'copy' if the rename should fail.

If this code is applied, It is advisable (not required) to store temp files on the same partition as uploaded files to improve performance.

**Comment by RomanBurunkov** [comment]
One thing I'm not sure that rename throws an error in case of different partitions. 
As far as I remember it doesn't do that and that is the reason why code had been changed to use copy instead of rename.

Do you now something about that?

**Comment by RomanBurunkov** [comment]
Hi @anneb ,

Thanks for checking that!
I'm going to merge that fix tomorrow morning.
