### ISSUE TITLE
<input ... multiple> doesn't work

### ISSUE THREAD

**Issue by flplv** [richardgirges/express-fileupload#17]
In case you have a multiple file selection input, such as 
```html
<input type="file" name="uploadedFiles" multiple>
```
it won't work. Multiple files will be uploaded, but they will not appear in the `files` tree since this line
```js
return req.files[fieldname] = {
```
(index.js line 53)
will be called one time per file, replacing the last file from the object.

 I'll submit a patch in this Issue soon.

**Comment by flplv** [comment]
This is a possible patch: https://github.com/flplv/express-fileupload/commit/2dcbb13938a4e26af1c782488eb014f5ff7c9f61?diff=split

The problem is that it will change the `req.files[fieldname]` from an Object to an Array, which will break backward compatibility. 

I believe the correct solution is to store files in `req.files[fieldname + "Multiple"]`, I just couldn't find a way to check if input is multiple file...

**Comment by r3wt** [comment]
@flplv its pretty simple to tell if its multiple files.

```js
if(req.files.hasOwnProperty(fieldName) && ref.files[fieldName] instanceof Array == false){
var tmp = req.files[fieldName];
req.files[fieldName] = [tmp];
}
else if(req.files.hasOwnProperty(fieldName) && ref.files[fieldName instanceof Array){
req.files[fieldName].push( newFileHere )
} else {
 //treat as single file
}
```

I hope this makes sense. i'm in the bed lol

**Comment by flplv** [comment]
Thanks.. gonna test it and create a PR.

**Comment by richardgirges** [comment]
I believe #18 fixes this. Updated and published to NPM registry.
