### ISSUE TITLE
Denial of Service by npm audit

### ISSUE THREAD

**Issue by adrianovieira** [richardgirges/express-fileupload#172]
This is a npm audit report for stable version like the last one: 1.1.5

Read more on https://www.npmjs.com/advisories/1216

**Comment by RomanBurunkov** [comment]
Has been fixed in 1.1.6-alpha.6

**Comment by bmoers** [comment]
how stable is 1.1.6-alpha.6?

**Comment by RomanBurunkov** [comment]
@bmoers ,

That is a good question.
Test coverage quite high and I don't have any issues and there is also no new issues on github, so I believe it is ok.

**Comment by RomanBurunkov** [comment]
Published 1.1.6.

**Comment by bmoers** [comment]
how come?
https://www.npmjs.com/advisories/1216/versions
Affected
1.1.6 an hour ago
Unaffected
1.1.6-alpha.6 a month ago

**Comment by RomanBurunkov** [comment]
Hi, see update from npm team: 

Hi,
Thank you for contacting the npm security team. It was a human mistake and is now fixed. We really appreciate the heads up!

Regards,
Andre E
npm security team
