### ISSUE TITLE
How to pass additional parameters to .mv method? Like { mkdirp: true } 

### ISSUE THREAD

**Issue by 7iomka** [richardgirges/express-fileupload#185]
Hi.
Without possibility to pass additional parameters to mv method i got errors, because output path not exist. MV lib for example have params `mkdirp: true ` and that create recursively needed folders if not exist.
Currently workaround is only with use tmp files like that
` mv(path.resolve(rootPath, tempFilePath), path.resolve(rootPath, `src/assets/${mId}/${name}`), { mkdirp: true }, err => {})`
Any ideas?
Thanks!

**Comment by RomanBurunkov** [comment]
I didn't quite catch the code you posted, but from the issue description, I believe you are asking about this option: createParentPath.

You should specify it in the middleware options like this:

```
app.use(fileUpload({
    useTempFiles : true,
    tempFileDir : '/tmp/',
    createParentPath: true
}));
```

**Comment by 7iomka** [comment]
Oh. my carelessness, sorry!
But still, as for me, this option should be enabled by default!
Thanks!
