### ISSUE TITLE
option to not create 0 bytes tmp files

### ISSUE THREAD

**Issue by hasnat** [richardgirges/express-fileupload#191]
Currently if no file is specified on form, this middleware creates a 0 bytes tmp file

**Comment by RomanBurunkov** [comment]
According to the source code, temp file could be created only in case file event came from busboy.
Could you please elaborate this issue, do you have a code example, debug output?

**Comment by hasnat** [comment]
I recall the case was where I had a form with like 20 file upload buttons, I only chose 1 file for upload and left others as is. On hitting form submit I had 19 0 byte files in temp folder with 1 file the one I chose before submit.

File uploads are optional on our application. 0 byte temp files however are always created.

**Comment by RomanBurunkov** [comment]
Hi @hasnat ,

Thanks for clarification.
I was able to reproduce that and looking into it.

**Comment by RomanBurunkov** [comment]
Example debug output:

> Express server listening on port  8000
> Temporary file path is /projects/express-fileupload-project/temp/tmp-1-1586164394213
> New upload started sampleFile->testfile.txt, bytes:0
> Temporary file path is /projects/express-fileupload-project/temp/tmp-3-1586164394215
> New upload started sampleFile1->tmp-2-1586164394215, bytes:0
> Temporary file path is /projects/express-fileupload-project/temp/tmp-5-1586164394217
> New upload started sampleFile2->tmp-4-1586164394217, bytes:0
> Uploading sampleFile->testfile.txt, bytes:20...
> Upload finished sampleFile->testfile.txt, bytes:20
> Upload sampleFile->testfile.txt completed, bytes:20.
> Upload finished sampleFile1->tmp-2-1586164394215, bytes:0
> Upload sampleFile1->tmp-2-1586164394215 completed, bytes:0.
> Upload finished sampleFile2->tmp-4-1586164394217, bytes:0
> Upload sampleFile2->tmp-4-1586164394217 completed, bytes:0.
>

**Comment by RomanBurunkov** [comment]
Hi @richardgirges , looks busboy fires file event even for empty form file fields.
Currently the only idea I have is to not open temporary file write stream until first data chunk came.

Not sure whether option needed for such case.

**Comment by RomanBurunkov** [comment]
See PR #210

**Comment by hasnat** [comment]
nice, I see PR would fix this issue, thanks!

**Comment by RomanBurunkov** [comment]
Ok, I'm merging that.
And will publish update in the npm tomorrow.

**Comment by RomanBurunkov** [comment]
Fixed in 1.1.7-alpha.3
