### ISSUE TITLE
.mv method is not waiting for execution

### ISSUE THREAD

**Issue by 1vipulp** [richardgirges/express-fileupload#193]
I am using .mv method to move files from one location to another, after that file which is at new location is being used for further processing. 

In most of the case, it is working properly, but sometime before moving file to new location, it is going to be used for other execution. 

Can I do await or any other process for .mv method ?

**Comment by richardgirges** [comment]
The `mv` function returns a Promise in the event that you do not pass the callback argument. So you can simply use the `await` keyword while executing `.mv`. Example:

```javascript
await file.mv('/some/dir/path');
```

Note this will NOT work if you are using callbacks: `file.mv('/some/dir/path', (err) => { })`

**Comment by richardgirges** [comment]
Marking as closed, please let me know if you need further assistance.

**Comment by 1vipulp** [comment]
Thanks, I got it.
