### ISSUE TITLE
dont use mv function in mac run

### ISSUE THREAD

**Issue by dayney** [richardgirges/express-fileupload#197]
"errno": -2,
  "code": "ENOENT",
   "syscall": "open",

**Comment by RomanBurunkov** [comment]
What does that mean?

**Comment by EngAhmedMahmoud** [comment]
@dayney @RomanBurunkov I have the same error but after updating the path for the uploaded directory it's working fine 
```js 
//before updating
sampleFile.mv(`../image/${sampleFile.name}`), function(err) {
     console.log(err);
  if (err) return res.status(500).send(err);
      res.send("File uploaded!");
 });

//after updating
    sampleFile.mv(path.join(__dirname, `../image/${sampleFile.name}`), function(
      err
    ) {
      console.log(err);
      if (err) return res.status(500).send(err);
      res.send("File uploaded!");
    });

```
```js
//here the complete route
const path = require("path");
const uploadImage = app => {
  app.post("/upload", function(req, res) {
    if (!req.files || Object.keys(req.files).length === 0) {
      return res.status(400).send("No files were uploaded.");
    }
    let sampleFile = req.files.doc;
    sampleFile.mv(path.join(__dirname, `../image/${sampleFile.name}`), function(
      err
    ) {
      console.log(err);
      if (err) return res.status(500).send(err);
      res.send("File uploaded!");
    });
  });
};
```

**Comment by RomanBurunkov** [comment]
Closing since no details provided.

**Comment by rmathias86** [comment]
I'm getting this error on mac as well. In my case (and might be the author's as well) this error occurs when the parent folder does not exist. Creating the bellow `upload` folder solves the issue. 

`[Error: ENOENT: no such file or directory, open '/Users/<hidden>/uploads/581C050B-A9AE-4533-937C-FD87190E4B40.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/<hidden>/uploads/581C050B-A9AE-4533-937C-FD87190E4B40.jpg'
}`
