### ISSUE TITLE
By using Express-fileupload library ,Upload image to AWS S3 bucket

### ISSUE THREAD

**Issue by softwaresolution357** [richardgirges/express-fileupload#204]
Hi sir,
any one please help me, by using express-fileupload library, I want to upload my file and image to AWS S3 bucket.

**Comment by RomanBurunkov** [comment]
Not sure how express-fileupload can help with that.

**Comment by richardgirges** [comment]
Hi @softwaresolution357 - agree with Roman on this one. What would be useful is if you looked up an AWS node tutorial for how to handle uploads to S3. 

This tutorial appears to cover AWS and express-fileupload, it might be of interest to you: https://medium.com/@snrsdev/mern-stack-aws-s3-express-fileupload-objectid-based-file-upload-for-profile-post-and-comment-acf386b5bb48

I hope this helps! Closing this issue out.

**Comment by aghosh0605** [comment]
Hi @softwaresolution357  Here is one solution for that
https://scanskill.com/backend/node-js/upload-to-s3-using-express-fileupload/
I hope it helps you to code what you want. Other options are:-
You can sote a file in local folder then upload the file in aws s3. There are many pacakges to parse form-data. You can use that to store the files in localstorage then after validation you can upload to s3.
