### ISSUE TITLE
CORS Blocked Access-Control-Allow-Origin when using mv() function.

### ISSUE THREAD

**Issue by asarycx** [richardgirges/express-fileupload#205]
I've read #30 didn't really helped much. so basically all of my request went okay except this one, that happens to have file upload, 

```Access to XMLHttpRequest at 'https://api.example.xyz/api/post' from origin 'https://app.example.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

the error seems to come from this this code
```
if (req.files) { <- this
      const fileRepo = getRepository(File);
      var newFile = new File();
      let file = req.files.thumbnail;

      var re = /(?:\.([^.]+))?$/;
      var extension = re.exec(file.name)[1];
      var title = slugify(
        new Date().toDateString() + new Date().getTime() + file.name
      );
       file.mv(`${process.cwd()}/public/image/${title}`, function(err) {
        if (err) return res.status(500).send(err);
      }); 

      newFile.name = req.body.name;
      newFile.file = title;
      newFile.type = "image";
      newFile.extension = extension;
      newFile.attribute = req.body.attribute;
      await fileRepo.save(newFile);
      newPage.thumbnail = newFile;
    }
```

~so this only happens when i use the express-fileupload, when i removed all express-fileupload usage in the code it works perfectly, any idea why is this happening?~

after some testing what actually cause this was the mv() function
```
       file.mv(`${process.cwd()}/public/image/${title}`, function(err) {
        if (err) return res.status(500).send(err);
      }); 
```
i removed this code alone, and the code works smoothly. any idea wy is this happening.

**Comment by simplenotezy** [comment]
This is most likely due to an issue on your backend, that prevents the CORS from being sent, most likely becasue the "mv" command fails, and outputs an error.
