### ISSUE TITLE
Files not populated and debug not logging any information

### ISSUE THREAD

**Issue by scryan7371** [richardgirges/express-fileupload#206]
I am trying to use express-fileupload to gain access to an uploaded file. I have created a simple test application to try and debug the issue.  I get an empty req.files object but the data is clearly in the body.  I have included the configuration and the endpoint code.  I am using

"express": "4.17.1",
 "express-fileupload": "1.1.6",

**My Configuration**

`
const app = express();

app.use(morgan('dev'));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(fileUpload({
  debug: true
}));
// Initialize the firebase app so you can use the validation
admin.initializeApp();
// Automatically allow cross-origin requests
app.use(cors({ origin: true }));
// Add middleware to authenticate requests
app.use(validateFirebaseIdToken);
const swaggerOptions = {
  explorer: true,
};
// build multiple CRUD interfaces:
console.log('Starting with API Description file');
console.log(swaggerSpec);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, swaggerOptions));
app.use('/api/v1', router);
`

**The Endpoint**

`
const upload = async (req: any, res: Response) => {

  const userUid = await getUserUidFromRequest(req);
  console.log(req.files);
  //console.log(req.body);
  console.log(String(req.body));
  if (!req.files || Object.keys(req.files).length === 0) {
    res.status(400).send('No files were uploaded.');
  } else {
`

Here is the printed output

null
null
  --------------------------d90472f5ebf0eb57
  Content-Disposition: form-data; name="file"; filename="testfile.txt"
  Content-Type: text/plain
  
  This is a test file so tell me I am ok
  
  --------------------------d90472f5ebf0eb57--

**Comment by RomanBurunkov** [comment]
You should check on client side that it sends a multipart form data.
I can't see consequent header in your output.

**Comment by scryan7371** [comment]
Here are the relevant parts of the request.  I am seeing the document in the body however it is not showing up in request.files and there is not logging from your code.   As you can see the file is very large 
  Any ideas??

`complete: true,
>    headers: {
>      host: 'localhost:5000',
>      connection: 'keep-alive',
>      'content-length': '6242086',
>      pragma: 'no-cache',
>      'cache-control': 'no-cache',
>      accept: 'application/json, text/plain, */*',
>      'sec-fetch-dest': 'empty',
>      authorization: 'Bearer  'xxx',
>      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36',
>      dnt: '1',
>      'content-type': 'multipart/form-data; boundary=----WebKitFormBoundaryOWuoX0ejytrRNPJK',
>      origin: 'http://localhost:3000',
>      'sec-fetch-site': 'same-site',
>      'sec-fetch-mode': 'cors',
>      referer: 'http://localhost:3000/admin',
>      'accept-encoding': 'gzip, deflate, br',
>      'accept-language': 'en-US,en;q=0.9,la;q=0.8'
>    },
`

**Comment by scryan7371** [comment]
It turns out that we are deployed on Google Cloud functions and they are modifying the request so none of the solutions work.  UGH...... I will close this
