### ISSUE TITLE
safeFileName

### ISSUE THREAD

**Issue by AlexNodex** [richardgirges/express-fileupload#21]
When safeFileName is set to true in the options, it removes the dot from the file extension thus rendering the extension useless, it might be an idea to allow dots also.

**Comment by bchr02** [comment]
that would explain why I am getting an unsupported MIME type error

**Comment by AlexNodex** [comment]
I really do hope the lib doesn't rely on file extension to set mime type, that would be extremely insecure to rely on !!

**Comment by bchr02** [comment]
I believe the MIME type error was coming from another lib that I am using in conjunction with express-fileupload as a result of the file extension missing..

**Comment by richardgirges** [comment]
> I really do hope the lib doesn't rely on file extension to set mime type, that would be extremely insecure to rely on !!

@AlexNodex that is certainly not the case. express-fileupload uses busboy to detect mime types. :)

As for this issue, thanks for bringing it up - it will be resolved in an upcoming release real soon.

**Comment by richardgirges** [comment]
[New release: v0.1.3](https://github.com/richardgirges/express-fileupload/releases/tag/v0.1.3) has been published to NPM. A new feature, courtesy of @pronein addresses this issue. 

You can now pass in `preserveExtension` as an option in the `express-fileupload` middleware. Example usage:

```javascript
app.use(fileUpload({ safeFileNames: true, preserveExtension: true }));
```

Read more detail about the feature on the [README](https://github.com/richardgirges/express-fileupload#available-options).
