### ISSUE TITLE
(node:18585) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by LukeXF** [richardgirges/express-fileupload#212]
Every so often I get `(node:18585) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated` using Node v12.13.

Please can you let me know if I'm looking in the right area or if you think this is another package throwing this warning? Any suggestion on how to fix this either way?

1. Researching this issue I see find 
https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames says `the http module OutgoingMessage.prototype._headers and OutgoingMessage.prototype._headerNames properties are deprecated.`

2. Searching for `prototype._header` in my node_modules returns 
![image](https://user-images.githubusercontent.com/6208873/78727073-90e98880-792b-11ea-8b22-3cbcf0c5ec90.png)

3. I see `"dicer": "0.3.0"` is a dependency of busboy

4. and I see `busboy": "^0.3.1"` is loaded as a dependency of this project https://github.com/richardgirges/express-fileupload/network/dependencies 

Do you think that by loading express-fileupload it is throwing this warning through its dependencies?

**Comment by RomanBurunkov** [comment]
Yeap, it looks so.
Should be addressed to busboy/dicer developer.

**Comment by RomanBurunkov** [comment]
Closing since it's a question about a package from the deps.
