### ISSUE TITLE
Wrong type declarations?

### ISSUE THREAD

**Issue by martinharder** [richardgirges/express-fileupload#216]
I try to access the properties "name" or "size" from the UploadedFile but in TypeScript I get the error:

`Property 'size' does not exist on type 'UploadedFile | UploadedFile[]'.
  Property 'size' does not exist on type 'UploadedFile[]'.ts(2339)`

The only solution is to remove `| UploadedFile[]` in line 23 of index.d.ts in @types/express-fileupload. But this can only be a temporary solution.

This issue was already reported here: https://github.com/richardgirges/express-fileupload/issues/156 but was marked as wantfix and was closed. Why? The type definition for this module is wrong and should be fixed.

Thank you in advance.

**Comment by RomanBurunkov** [comment]
Hi @martinharder 

This module doesn't have own declarations and it looks that declarations you've got has been created by:

// Project: https://github.com/richardgirges/express-fileupload#readme
// Definitions by: Gintautas Miselis <https://github.com/Naktibalda>
//                 Sefa Ilkimen <https://github.com/silkimen>
//                 Tomas Vosicky <https://github.com/vosatom>
//                 Piotr Błażejewicz <https://github.com/peterblazejewicz>

I believe u can try address with issue to Piotr Błażejewicz it look that he is one of the authors of that declarations.

**Comment by Roman991** [comment]
> I try to access the properties "name" or "size" from the UploadedFile but in TypeScript I get the error:
> 
> `Property 'size' does not exist on type 'UploadedFile | UploadedFile[]'. Property 'size' does not exist on type 'UploadedFile[]'.ts(2339)`
> 
> The only solution is to remove `| UploadedFile[]` in line 23 of index.d.ts in @types/express-fileupload. But this can only be a temporary solution.
> 
> This issue was already reported here: #156 but was marked as wantfix and was closed. Why? The type definition for this module is wrong and should be fixed.
> 
> Thank you in advance.

there u can find also the solution
`req.files[index:string` >> its the file name`].propertyName` >> name, mv, mimetype ...etc 
so just delete the `| UploadedFile[]` at line 23 of d.ts

**Comment by RomanBurunkov** [comment]
Closing since that doesn't look like a express-fileupload issue

**Comment by Relaxe111** [comment]
You need to explicitly to declare field file as UploadedFile[]  like:
`const file = req.files.file as UploadedFIle[]`

**Comment by Relaxe111** [comment]
explainded litte bit more [here](https://github.com/richardgirges/express-fileupload/issues/156)

**Comment by thegregthomp** [comment]
@Relaxe111 I'm just seeing this but your example didn't help. Not sure if something changed. The only way I can get this to work is to remove the ` | UploadedFile[]` from the types definition.

**Comment by thegregthomp** [comment]
@martinharder I know it was a long time ago but did you ever find a workaround?

**Comment by r3wt** [comment]
@thegregthomp try `const file = req.files.file as UploadedFile;` if `file` is a single file and not an array of uploaded files.

**Comment by thegregthomp** [comment]
@r3wt thanks for the timely response. I've tried this and get: 

> src/controllers/files/upload.controller.ts:31:50 - error TS2304: Cannot find name 'UploadedFile'.

`const attachedFile = req.files.attachment as UploadedFile;`

**Comment by thegregthomp** [comment]
@r3wt I saw another suggestion using `fileUpload.UploadedFile` but this also didn't work. I honestly can't find a way around this issue.

**Comment by r3wt** [comment]
@thegregthomp you have to import/require `UploadedFile` type definition as if it were any other variable. you can try `import {UploadedFile} from 'express-fileupload';`. typescript will know to load it from the definitions.

**Comment by thegregthomp** [comment]
@r3wt Thanks so much for the help, this worked. My experience with TS is limited but I thought if it was in the `@types` directory the types would be available in the global space. Is this fix to circumvented the global definition bug?

**Comment by r3wt** [comment]
@thegregthomp the bug is here at Line 14
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-fileupload/index.d.ts#L14

I am not the most proficient at typescript, nor have i used it with express/express-fileupload yet, but i think this should work to support named fields on `req.files`:

```
declare global {
    namespace Express {
        interface Request {
            files?: fileUpload.FileArray | { [key:string]: fileUpload.FileArray; };
        }
    }
}
```

**Comment by euroclydon37** [comment]
I'm kinda confused why `req.files.file` can be an array. To me, if multiple files were being uploaded, I would expect `req.files` to simply have multiple file names attached to it (`req.files.fileA` and `req.files.fileB` for example). Am I misunderstanding something?
