### ISSUE TITLE
req.files undefined

### ISSUE THREAD

**Issue by lntel** [richardgirges/express-fileupload#220]
Hey, I've been trying to upload image files using the `fetch` API and when logging `req.files` it just comes out as undefined. I've also tried using a `FormData` interface which returns null also.

Client
```js
export const uploadRequest = async (endpoint, file, cb) => {

    fetch(`${Api}${endpoint}`, {
        method: 'POST',
        body: file
    })
    .then(response => {
        cb(response);
        console.log(response);
    })

};
```

Server
```js
exports.uploadImage = async(req, res) => {
    if(!req.files) {
        return res.status(400).send('No files uploaded');
    }

    console.log(req.files)

    res.send('test');
};
```

Any guidance would be appreciated. Thanks.

**Comment by RomanBurunkov** [comment]
That definitely something wrong with your post request.
With fetch you should do it in this way:

`
let form = document.querySelector('#uploadForm')
let inpFile = document.querySelector('#inpFile')
form.addEventListener('submit', async event => {
    event.preventDefault()
    const formData = new FormData()
    formData.append('inpFile', inpFile.files[0])
    fetch('http://myip/upload', {
        method: 'POST',
        body: formData
    }).catch(console.error)
})
`

**Comment by RomanBurunkov** [comment]
See example below which works for me:

```
<html>
  <body>
    <form id='uploadForm' method='post' encType="multipart/form-data">
      <div style="margin: 10px;"><input id="inpFile" type="file" name="sampleFile" /></div>
      <div style="margin: 10px;"><input type='submit' value='Upload!' /></div>
    </form>
    <script>
      const form = document.querySelector('#uploadForm');
      const inpFile = document.querySelector('#inpFile');

      form.addEventListener('submit', (e) => {
        e.preventDefault();
        const formData = new FormData();
        formData.append('inpFile', inpFile.files[0]);
        fetch('/upload', { method: 'POST', body: formData})
          .then(res => res.text())
          .then(alert)
          .catch(console.error);
      });
    </script>
  </body>
</html>
```

**Comment by beauxq** [comment]
>         const formData = new FormData();
>         formData.append('inpFile', inpFile.files[0]);
>         fetch('/upload', { method: 'POST', body: formData})
>           .then(res => res.text())
>           .then(alert)
>           .catch(console.error);

I think it would be good to put this in the "Usage" section of the readme.

The Usage should show what it looks like on both client and server.
