### ISSUE TITLE
filename in hebrew fonts

### ISSUE THREAD

**Issue by omeriko** [richardgirges/express-fileupload#221]
Hi There, 

We're using this highly practical package in our project, so far we've been very happy. 

However today we've found out that if the client uploads a file that it's name is in Hebrew fonts the **req.files.file_param.name** field has the following gibberish value: "�� ����� �������.html"

What should we do in order to receive the actual fonts? 

Thanks,
Omer

**Comment by RomanBurunkov** [comment]
Have you tried 'uriDecodeFileNames' option?
