### ISSUE TITLE
Set createParentPath=true by default

### ISSUE THREAD

**Issue by vrg-success** [richardgirges/express-fileupload#223]
Hi, I spend to many times to understand why I get Error:

```js
Error: ENOENT: no such file or directory, open 'C:\\Users\\someDir\\0fj8gv_yyc1rutram4w7z7n_ziw.jpg'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\someDir\\0fj8gv_yyc1rutram4w7z7n_ziw.jpg'
}
```

Please set value false by default for option createParentPath, I think it will help of people

**Comment by RomanBurunkov** [comment]
Option described in the docs and it also possible that for many projects users don't need other module to create paths.
So I do not see any necessity to set it true by default.
