### ISSUE TITLE
sampleFile.mv is not defined

### ISSUE THREAD

**Issue by sirius2013** [richardgirges/express-fileupload#23]
Hi, I tried this sample.
but I got below error.
sampleFile.mv is not defined
![image](https://cloud.githubusercontent.com/assets/5020713/24329148/b18e30ba-122f-11e7-9372-a09dedc205cd.png)

**Comment by richardgirges** [comment]
Hi @sirius2013 

My first theory is that perhaps the upload isn't taking place correctly. Would you mind showing me your logic for uploading the file, alongside your full `console.log` output of `req.files.sampleFile` ?

**Comment by richardgirges** [comment]
Hey @sirius2013 any word?

**Comment by aaronorosen** [comment]
@sirius2013 i'm guessing the problem is this: 

  // The name of the input field (i.e. "sampleFile") is used to retrieve the uploaded file 
if you don't use that name on your input form you'll need to upload the server side code.

**Comment by a244096658** [comment]
Hi! I got the same error. As expected, the req.files.myfile should be like: 
![image](https://cloud.githubusercontent.com/assets/20459763/25967296/57ce12ee-3696-11e7-928d-d5bba375eeba.png)

But what I got in my code is: 
![image](https://cloud.githubusercontent.com/assets/20459763/25967328/7359484e-3696-11e7-8e0c-a12f2b234c3c.png)

**Comment by mission10138** [comment]
mv doesnt seem to work at all.

**Comment by Allmektiger** [comment]
I confirm that issue.
console.log(req.files.avatar) shows:
`{ fieldname: 'avatar',
  originalname: 'image001.jpg',
  name: 'c5c6bd366ff0747d60bdea6fe423b7d6.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  path: '/tmp/c5c6bd366ff0747d60bdea6fe423b7d6.jpg',
  extension: 'jpg',
  size: 56253,
  truncated: false,
  buffer: null }`
but when i try to invoke req.files.avatar.mv at next row i receive
`req.files.avatar.mv is not a function TypeError: req.files.avatar.mv is not a function`
NodeJS v6.11.0

**Comment by richardgirges** [comment]
@Allmektiger thanks for the details. Would you mind providing me with additional information to help me track this issue down? Such as your express and middleware setup?

Your output of `req.files.avatar` doesn't look like a valid `express-fileupload` object - it seems that perhaps something else is handling the upload for your file (i.e. another middleware).

To everyone else experiencing this issue, some additional info would be greatly appreciated:
- Version of Node
- Your express setup (i.e. your code for setting up express middlewares)

**Comment by Allmektiger** [comment]
Yes, of course.
I use keystonejs 4.0: https://github.com/keystonejs/keystone
NodeJS as i say, v6.11.0

At /routes/index.js:
`... 
app.all('/server?', keystone.middleware.api, routes.views.server); 
...`

At routes.views.server:

var keystone = require('keystone');
var fileUpload = require('express-fileupload');
<...>
if (req.files) {
              console.log(req.files.avatar);
              req.files.avatar.mv('../../public/images/users/'+req.body.login+'.'+req.files.avatar.extension, function(err) {
<...>

That is code about "mv is not a function"

**Comment by Allmektiger** [comment]
Ouch, I found that keystonejs has already defines req.files. Sorry to bother you.

**Comment by richardgirges** [comment]
Not a problem! That's actually pretty helpful. I suspect something similar may be happening with the other users.

**Comment by r3wt** [comment]
wow what a fucking moron

**Comment by r3wt** [comment]
Keystone probably uses another file upload middleware already. After all, fileuploads a native type of keystone List models... good grief
