### ISSUE TITLE
Is it possible to change filename?

### ISSUE THREAD

**Issue by msankar1991** [richardgirges/express-fileupload#24]
Currently working REST API for uploading the documents to user profile. Is there anyway to change the file name before moving to particular folder. Like I need to change the file name dynamically example for user profile name need to store based userId.

**Comment by pronein** [comment]
Yes. Using the `mv(...)` function on the uploaded file you can rename the file to whatever you choose as seen in the readme.
```
...
let sampleFile = req.files.sampleFile;

sampleFile.mv('/somewhere/on/your/server/filename.jpg', function(err) {
    if (err)
      return res.status(500).send(err);

    res.send('File uploaded!');
  });
```
In this case, the file was originally named with the value found in `sampleFile.name` but it is being renamed to `filename.jpg` in the sample above. If you need to rename your file, just determine the name and append it to the end of the path provided to `.mv(...)` and the file will be renamed on your server.

**Comment by richardgirges** [comment]
@msankar1991 it looks like @pronein has answered your question. Closing this out - please let me know if you need any additional information. Thanks!
