### ISSUE TITLE
Error: Unknown system error -122 

### ISSUE THREAD

**Issue by RobertoGlez** [richardgirges/express-fileupload#250]
What meaning  this? 
the full log is:
 [Error: Unknown system error -122: Unknown system error -122, close]
  errno: -122,
  code: 'Unknown system error -122',
  syscall: 'close'

this happen when I excecute .mv() function 

OS: Cetos8
Nodejs: v10.21.0
express: 1.1.7-alpha.3

**Comment by SymbolCsaba** [comment]
#define EDQUOT.    122

It may be quota error when disk operation (mv). Or simple disk full?

**Comment by RomanBurunkov** [comment]
Closing this as a not active issue highly likely related to the underneath system and it's configuration rather than middleware.
