### ISSUE TITLE
Upload by JS not working

### ISSUE THREAD

**Issue by Debdut** [richardgirges/express-fileupload#251]
When using the html template it works

```html
<form action='http://localhost:8000/upload' method='post' encType="multipart/form-data">
  <input type="file" name="sampleFile" />
  <input type='submit' value='Upload!' />
</form> 
```

But when I upload by JS instead of Form Submit it doesn't work

```html
<input id="input" type="file" name="sampleFile" />
```
```js
const input = document.querySelector('#input')
input.addEventListener('change' (event) => {
  const files = event.target.files
  fetch('http://localhost:8000/upload', { method: 'post', files })
})
```

In server `req.files` is `undefined`

**Comment by Debdut** [comment]
i also tried `FormData` already, doesn't work

**Comment by SirCQQ** [comment]
Try changing the 'addEventListener' from "change" to "submit". 

You are trying to create a FormData object and execute a fetch every time you change something in the form.  

P.S. 
Here ` const files = event.target.files

  const body = new FormData()
  body.append('files', files)`
Try to append `files[0]` 

Hope it helps 😄

**Comment by Debdut** [comment]
Nope it doesn’t work

**Comment by duterte** [comment]
This thing has not been fixed yet ?

**Comment by richardgirges** [comment]
I need to see your server code. It sounds like you are not loading the express fileupload middleware properly.

**Comment by duterte** [comment]
> I need to see your server code. It sounds like you are not loading the express fileupload middleware properly.

I'm having this the same scenario in which I need to upload file (Images for instance) using fetch API, but looks like it was not supported yet.

**Comment by richardgirges** [comment]
I cannot help without seeing your node code. All I know is that it “doesn’t work” but I have no code or reproducible issue to go off of. Please provide code showing your issue so that I can assist.

At the moment I am able to upload code just fine with JS and all of our tests are passing.

**Comment by duterte** [comment]
> I cannot help without seeing your node code. All I know is that it “doesn’t work” but I have no code or reproducible issue to go off of. Please provide code showing your issue so that I can assist.
> 
> At the moment I am able to upload code just fine with JS and all of our tests are passing.

This is a code snippets on front-end, which is trying to upload file using fetch API

![front-end js file](https://user-images.githubusercontent.com/16894560/96079470-6c2c2a00-0ee7-11eb-8015-847c4235d66e.JPG)

This is a code snippets on nodeJS which tries to log to the console the req.files object

![nodejs file](https://user-images.githubusercontent.com/16894560/96079640-d3e27500-0ee7-11eb-8553-b2ab96398381.JPG)

But it logs undefined in the console.

![consoles log](https://user-images.githubusercontent.com/16894560/96079682-ec528f80-0ee7-11eb-9e10-c3da735f6551.JPG)


Maybe because I did not use html form to upload the file, Instead I used browser's built-in fetch API

**Comment by SirCQQ** [comment]
Try this in the node file
```javascript
const express = require("express");
const fileUpload = require('express-fileupload');

const app = express();

app.use(fileUpload({
    createParentPath: true
}));

app.post("/post_image", (req,res)=>{
   console.log(req.files);
return res.send("Done");
})
```

And for the request you should use `content-type:multipart/form-data`  header so the middleware can understand that a file is sent, the default header is `application/x-www-form-urlencoded`. 

You should use the specific headers for the specific request. 

Hope it helps.

**Comment by duterte** [comment]
Hi I just wanted all to know that the procedure provided above made by @SirCQQ  solves the problem

**Code snippets in front-end** 

![front-end](https://user-images.githubusercontent.com/16894560/96089474-79521480-0ef9-11eb-8fdf-e7b232432394.JPG)

**Code in backend**

![node js](https://user-images.githubusercontent.com/16894560/96089493-7d7e3200-0ef9-11eb-8626-54a6fe86f47c.JPG)

**console log**

![console log](https://user-images.githubusercontent.com/16894560/96089501-80792280-0ef9-11eb-91c1-3f39ad735fef.JPG)
