### ISSUE TITLE
Page reloading after uploading same file

### ISSUE THREAD

**Issue by Sofronijev** [richardgirges/express-fileupload#268]
Hi,

After a few days of bug searching, I found out that newer versions of react-scripts are making page reload when I upload the same file. I tested this with version 3.0.1, 3.4.3, 4.0.3, it only works on  3.0.1 and lower. 

You can use this example to recreate the bug https://github.com/bradtraversy/react_file_uploader
Just update react-scripts to the latest version and it will start reloading the page after upload, but only when the file is already uploaded. I used `debug: true` but it's not showing anything strange.

On the project that I'm working on, I get this error a lot `Express-file-upload: Request is not eligible for file upload!`, I thought it would disappear after I downgrade react-scripts but it's still here and It also happens when I just reload the page or go to any other page in the app.

**Comment by cristiancosano** [comment]
Check if your form has encType="multipart/form-data" attribute and post method (get and head not are eligibles.

**Comment by Sofronijev** [comment]
Looks like the issue resolved itself, I didn't change anything.
