### ISSUE TITLE
Previously it was working well but today all req.files is null

### ISSUE THREAD

**Issue by hannzern** [richardgirges/express-fileupload#272]
I am following the documentation by using

app.use(fileUpload({
    useTempFiles: true,
    tempFileDir: '/tmp/',
    debug: true
}))

In my request, I am logging the req.files but the return is null I have tried form-data using POSTMAN and also on my frontend javascript side but it is returning null. Previously (yesterday and before) it was working totally fine but today the req.files is always null. I am currently on 1.2.1

**Comment by robogeek** [comment]
Any knowledge about this?  I'm having the same problem.

**Comment by robogeek** [comment]
Actually, I solved my problem -- had to do with the HTML of the input tag of the file selector in the FORM.  Once I fixed that, the code worked.
