### ISSUE TITLE
Can we not upload the file to the server ?

### ISSUE THREAD

**Issue by pioupia** [richardgirges/express-fileupload#280]
Hi !
Your package works really well. Unfortunately, I do not want to upload the file to my server but only kept the buffer that we do not get. Is there a function to avoid uploading files to the server ?

Thank you in advance !
Have a great day !

**Comment by RomanBurunkov** [comment]
Remove useTempFiles option or set it to false and also do not call file.mv method.
file.data will be a buffer containing the uploaded file.
