### ISSUE TITLE
How to remove image

### ISSUE THREAD

**Issue by TOcvfan** [richardgirges/express-fileupload#282]
How do I remove an image from the server?

**Comment by RomanBurunkov** [comment]
Please elaborate your request.

**Comment by RomanBurunkov** [comment]
Closing.
Looks it is not related to this package.

**Comment by TOcvfan** [comment]
Express-file upload allows you to upload files, but how do I delete them again so that they don't take up space, I have seen that there is a a temperay file option, but it doesn't say how long it will be there or how to set the time..

**Comment by RomanBurunkov** [comment]
There is no timeouts or timers for temporary files.
Mean it's up to your app logic.

Module just uploads files.
And you decide what to do with them.

But  file object has a mv method, in case of temporary files it moves file to the destination directory.

Hope it's clear now
