### ISSUE TITLE
[Question]: FileUploader Limit Option is measured in KB?

### ISSUE THREAD

**Issue by apenasigordev** [richardgirges/express-fileupload#288]
Is the FileUploader option measured in KB or MB?

**Comment by apenasigordev** [comment]
If you have an answer, I appreciate it :)

**Comment by Spiderjockey02** [comment]
bytes, for example:
![image](https://user-images.githubusercontent.com/55885015/134787379-f313fff4-c5fc-4272-a0aa-83335eeb29df.png)

**Comment by apenasigordev** [comment]
tysm for responding!
