### ISSUE TITLE
Migrate to busboy fork since original is no longer supported

### ISSUE THREAD

**Issue by kibertoad** [richardgirges/express-fileupload#297]
Hi! We've forked the original busboy within fastify organization in order to address known security issues and optimize performance. Here you can see the full list of changes: https://github.com/fastify/busboy/blob/master/CHANGELOG.md

Would you be interested in a PR switching over to `@fastify/busboy`? Unfortunately, it would have to be a semver major, since we only support Node 10+, and your project is still on Node 8, from what I can see. But other than that, there should be no breaking changes.

**Comment by richardgirges** [comment]
Hello, we're about to stop supporting Node versions < 12. I'm in the middle of a significant upgrade. Happy to look into switching to your version of busboy afterward, although I do want to spend some time considering leaving busboy altogether.

**Comment by richardgirges** [comment]
Hello, it appears the original is still supported. Can you please clarify?

**Comment by kibertoad** [comment]
@richardgirges Yeah, author did resume development since the fork was created, so simply updating to latest busboy is an option now.

**Comment by richardgirges** [comment]
Closing since busbuy support has resumed

**Comment by kapouer** [comment]
Note that busboy is stalling and fastify/busboy is even used in nodejs core now.
