### ISSUE TITLE
Can't upload multiple files at the same time

### ISSUE THREAD

**Issue by DejvoVIII** [richardgirges/express-fileupload#3]
or i don't know how to do it

**Comment by richardgirges** [comment]
@DejvoVIII you can upload multiple files. All uploaded files can be found in the `req.files` object.  

For example, if you have these two fields in your multipart form:

```
<input type="file" name="profilePhoto" />
<input type="file" name="coverPhoto" />
```

On form submission, in express, you can access these files by the name of their input field:
```
console.log(req.files.profilePhoto);
console.log(req.files.coverPhoto);
```

Please re-open this issue if you're still running into problems uploading multiple files.

**Comment by DejvoVIII** [comment]
I didn't mean that. I ment when you've got select type multiple and then select multiple files, it uploads just the first one

**Comment by richardgirges** [comment]
I'm going to need more detail. Can you provide an example of what you're trying to do?

**Comment by DejvoVIII** [comment]
`<form ref='uploadForm' id='uploadForm' action='http://localhost:3000/upload' method='post' encType="multipart/form-data">
	<input type="file" name="sampleFile" multiple />
	<input type='submit' value='Upload!' />
</form>`

The input has a "multiple" parameter, so in the selection window you can select multiple files at once but the `req.files` contains just the first file that you selected.
