### ISSUE TITLE
Getting "No 'Access-Control-Allow-Origin' header is present on the requested resource." error

### ISSUE THREAD

**Issue by RohitRane** [richardgirges/express-fileupload#30]
XMLHttpRequest cannot load https://localhost:4000/upload-file. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 500. 

I have enabled on my Express server by doing : 

```
const fileUpload = require('express-fileupload');
app.use(fileUpload());

app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Cache-Control, Key, Access-Control-Allow-Origin");
    next();
});

```
But, all my other REST POST routes are working fine except the '/upload-file' route which uses your middleware.  The request is not even reaching the controller.

And BTW the '/upload-file' route works perfectly fine when tested with POSTMAN. So there is no problem with logic

Nothing seems to work what do I need to do?

BTW I am using an angular-cli based angular js front end with Dropzone.js as a file upload plugin.

**Comment by richardgirges** [comment]
Hi @RohitRane, thanks for the detailed report. I would venture to guess that you need to add your `Access-Control-Allow-Origin` logic _before_ the `fileUpload` middleware for starters, as your CORS logic should execute before any other request handling logic.

Can you give that a try and let me know if it worked?

**Comment by r3wt** [comment]
@richardgirges I have cors after the file upload, and a ton of other middleware, and it works fine

```js

 // handle application/json forms
app.use(bodyParser.json()); // handle application/json forms

// handle application/x-www-form-urlencoded forms
app.use(bodyParser.urlencoded({ extended: true })); 

//file upload
app.use(fileUpload({
	limits: { 
		fileSize: 1 * 1024 * 1024,
		fields: 50,
		files: 1,
		parts: 51,
	}
}));

// nginx reverse proxy(unsafe if app is bound to the public ip address)
app.enable('trust proxy');
app.set('trust proxy',function(){ return true; });

// cors
app.use(function(req, res, next) {
	res.header('X-Frame-Options','SAMEORIGIN');
	res.header('Access-Control-Allow-Credentials', true);
	res.header('Access-Control-Allow-Origin', '*');
	res.header('Access-Control-Allow-Methods','GET,PUT,POST,DELETE');
	res.header('Access-Control-Allow-Headers','X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept');
	next();
});
```

**Comment by richardgirges** [comment]
Thanks @r3wt, good point. 

I'd find it highly unlikely that the CORS issue is directly related to this library, as this is just a simple middleware. But stranger things have happened I guess. My leading theory is that perhaps something in the multipart AJAX request is sending some sort've header that your CORS rules are not allowing. 

@RohitRane according to [this ticket](https://github.com/enyo/dropzone/issues/354#issuecomment-170601842), Dropzone requires `X-File-Name` in your `Access-Control-Allow-headers`. 

If you have a sample app with Dropzone in it, that's using express-fileupload, I'm happy to try debugging it.

**Comment by RohitRane** [comment]
Sorry for the delayed response due to  the weekend. I'll try the solutions you guys have mentioned and get by to you by EOD.

**Comment by RohitRane** [comment]
If I moved fileupload initialization after the CORS like this : 

```
const fileUpload = require('express-fileupload');

app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Cache-Control, Key, Access-Control-Allow-Origin");
    next();
});
app.use(fileUpload());
```
But then I am getting this error 

```
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <link rel='stylesheet' href='/stylesheets/style.css' />
  </head>
  <body>
    <h1>Multipart: Boundary not found</h1>
<h2></h2>
<pre>Error: Multipart: Boundary not found
    at new Multipart (/home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/busboy/lib/types/multipart.js:58:11)
    at Multipart (/home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/busboy/lib/types/multipart.js:26:12)
    at Busboy.parseHeaders (/home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/busboy/lib/main.js:71:22)
    at new Busboy (/home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/busboy/lib/main.js:22:10)
    at processMultipart (/home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/express-fileupload/lib/index.js:51:12)
    at /home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/express-fileupload/lib/index.js:20:5
    at Layer.handle [as handle_request] (/home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/router/lib/layer.js:93:5)
    at trim_prefix (/home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/router/index.js:335:13)
    at /home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/router/index.js:299:7
    at Function.process_params (/home/kpatra/workspace/repo/vems/LKMonitoring/lkmonitoring-express/node_modules/router/index.js:354:12)</pre>

  </body>
</html>

```

**Comment by RohitRane** [comment]
Actually @richardgirges  solution  worked, the "Boundary not found" was caused because I was explicity  setting 'Content-Type': 'multipart/form-data' in the Dropzone plugins header option. Once I removed it, it worked fine.
