### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [richardgirges/express-fileupload#305]
Hey there!

I belong to an open source security research community, and a member (@harunoz) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by harunoz** [comment]
Thank you for your help Jamie.

**Comment by richardgirges** [comment]
Hi Jamie and Harun,

Here is the SECURITY.md file:
https://github.com/richardgirges/express-fileupload/blob/master/SECURITY.md

I am currently the only maintainer on this project. I would appreciate any
support in the form of PRs (whether it's actual security fixes or simply
reporting known security vulnerabilities).

Thanks,

Richard

**Comment by JamieSlome** [comment]
@richardgirges - thanks for your support!

We have already sent an e-mail to your elected address, have you been able to see this in your inbox?

You can also view the report directly here:
https://huntr.dev/bounties/1d096e50-04ee-42b2-abd1-786f5c750851/

It is private and only accessible to you! 👍
