### ISSUE TITLE
req.files is undefined

### ISSUE THREAD

**Issue by Okpyard** [richardgirges/express-fileupload#306]
I use this code 
`const express = require('express')
const app = express()
const port = 3000
const fileupload = require("express-fileupload");
app.use(fileupload());

app.post("/", (req, res) => {
  if (!req.files) {
    res.send("File was not found");
    return;
  }

  const file = req.files.file;
  res.send(`${file.name} File Uploaded`);
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})`

but  req.files is undefined
<img width="939" alt="Screenshot 2022-03-13 at 18 20 58" src="https://user-images.githubusercontent.com/89247320/158066710-5a56ddad-75bc-4ca8-9083-5a0403f0d106.png">

**Comment by malletgaetan** [comment]
Hi,

your code is working just fine, ensure that you're correctly using postman (it seems correct from the image), if you're still  facing this issue, please share your express and express-fileupload version

**Comment by nischay2x** [comment]
"express": "^4.17.3",
    "express-fileupload": "^1.3.1",
Mine is this, and I am getting the same error. It was working fine 1 week ago.

**Comment by sergiorivera50** [comment]
@nischay2x @Okpyard 
Remove the file from the body request in Postman and add it again. It is a known bug that hasn't been solved yet.
