### ISSUE TITLE
tmp file isn't deleted if failed to .mv

### ISSUE THREAD

**Issue by malletgaetan** [richardgirges/express-fileupload#307]
# problem
if using tmp files for upload, in the case the file.mv fails, tmp file isn't removed#305 

# version
1.3.1

# fix
in the case this is in fact not wanted, i'll give it a shot for pr

**Comment by richardgirges** [comment]
This sounds like intentional behavior to me. It should be up to the user to delete any auto-generated temp folders in the event that the `.mv` method fails.
