### ISSUE TITLE
preserveExtension has no use in the library?

### ISSUE THREAD

**Issue by victorsferreira** [richardgirges/express-fileupload#309]
I realized that my uploads aren't working with version 1.3.1. I tried to check the internals, and am I wrong or `preserveExtension` is doing nothing right now?

Anytime I turn `useTempFiles` to true it creates files with the name like `tmp-1-1648177925863` and never preserve the file extension.

This is my code right now

 ```
this.app.use(fileUpload({
            debug: true,
            useTempFiles: true,
            safeFileNames: false,
            preserveExtension: true,
            tempFileDir: path.join(__dirname, '../' , 'uploads')
        }));
```

The expected behavior is a file with name `user.jpg` is uploaded to a folder `./uploads` and the final file looks like
`./uploads/tmp-1-1648177925863.jpg`

**Comment by samiy803** [comment]
> Preserves filename extension when using safeFileNames option.

So it looks like preserveExtension only matters when safeFileNames is set true. Otherwise, the file name remains unchanged.

**Comment by richardgirges** [comment]
Yes this only works in conjunction with safeFileNames
