### ISSUE TITLE
while I upload no file with just submitting, req.files is {}, and !req.files will be false.

### ISSUE THREAD

**Issue by xliez** [richardgirges/express-fileupload#31]
So that can't deal with empty input[type='file'].

**Comment by xliez** [comment]
Also, req.body can't get the input[type='text'] when it along with input[type='file']

**Comment by richardgirges** [comment]
Hey there,
I intentionally left `req.files` as an empty object to follow the same conventions that other Express middlewares. Usually `req.body` and `req.query` will be empty objects when no arguments are passed in as body or query parameters. 

As for the issue of `input[type=text]` not getting parsed by `express-fileupload` properly, this sounds like it may be a bug. Can you let me know what kind of headers you were sending in your request? i.e. multipart or urlencoded?  Thanks!

**Comment by xliez** [comment]
Thanks, I got it!
The header is multipart. I defined the form with the attribute `enctype="multipart/form-data"`.

**Comment by leviwheatcroft** [comment]
I think what OP is getting at re `!req.files == false` is from the example in the readme:

```
if (!req.files)
    return res.status(400).send('No files were uploaded.');
```

if `req.files` is `{}` when no files are received, then this if statement will never be true.

**Comment by ryanshores** [comment]
Maybe the readme should be updated. I fixed it by checking for an empty object using 
`if( Object.keys( req.files ).length == 0 )`

**Comment by richardgirges** [comment]
@MichaelE1 just updated the documentation. Sorry about the confusing docs on this one! @ryanshores's approach is definitely the right way to go when checking for a zero-file upload.
