### ISSUE TITLE
How to upload a file in express with progress bar?

### ISSUE THREAD

**Issue by rajkuttie** [richardgirges/express-fileupload#32]

**Comment by UnknownHero** [comment]
Hi!
Your issue related with browser and don't related with express.

You can find answer here:
http://christopher5106.github.io/web/2015/12/13/HTML5-file-image-upload-and-resizing-javascript-with-progress-bar.html

https://stackoverflow.com/questions/15410265/file-upload-progress-bar-with-jquery

**Comment by richardgirges** [comment]
@rajkuttie Please let me know if @UnknownHero has answered your question. Getting the progress of your download is definitely a client-side integration. Happy to discuss further! Closing the issue for now since there is no actionable takeaway for express-fileupload.

**Comment by AirplanegoBrr** [comment]
Hello. I am kinda confused about how to do this...
I want to be able to put the progress of the current file being uploaded on a new get request. Kinda like what is done [here](https://stackoverflow.com/a/31529434) they put the progress of the current file in a new get I'm not sure how I would convert this to using express and not HTTP

Also, I know I should probably make a new issue but I'm gonna reply here as this is about the thing I'm trying to do
