### ISSUE TITLE
"errno":-4058,"code":"ENOENT","syscall":"open"

### ISSUE THREAD

**Issue by Umesh2Patel** [richardgirges/express-fileupload#33]
Hi, I am using sampleFile.mv. It was working before but recently I am seeing below exception. I am using Postman tool to make a call. I tried using RestClient tool and seeing same error.

Response:
{
    "errno": -4058,
    "code": "ENOENT",
    "syscall": "open",
    "path": "C:\\Users\\QATools\\testdb-api\\Users\u000bn0u7yzDesktopOmniture excels files - Copy\\omniture-test-data.xlsx"
} 

![upload api issue](https://user-images.githubusercontent.com/12166016/27197303-926eea80-51c2-11e7-8872-24e0edb963ca.JPG)

Below is the code i am using:-
var express = require('express')
const fileUpload = require('express-fileupload');
app.post('/uploadfile', function(req, res) {
  if (!req.files)
    return res.status(400).send('No files were uploaded.');

  // The name of the input field (i.e. "sampleFile") is used to retrieve the uploaded file

  let sampleFile = req.files.file;
  console.log(req.files.file);

  var filename = req.files.file['name'];
  console.log(filename);
  // Use the mv() method to place the file somewhere on your server
  sampleFile.mv('C:\Users\user\Desktop\Omniture excels files - Copy/'+filename, function(err) {
    if (err)
      return res.status(500).send(err);

    res.send('File uploaded!');
  });
});

**Comment by richardgirges** [comment]
Hey @Umesh2Patel can you show me what headers you're sending? Trying to replicate this on my end. Thanks!

**Comment by richardgirges** [comment]
@Umesh2Patel any word? Trying to get more information on what kind of headers you're sending so I can replicate this issue on my end.

**Comment by Umesh2Patel** [comment]
@richardgirges  Thanks for following up. After changing my code I am not seeing my error anymore. 
Below is my API. I have added {force:true} and then it started working. 
 
 app.post('/deletefiles', function(req, res) {
  del(['/app/new-omniture-tests/omniture-tests/omnitureUtilities/*.xlsx'], {force: true}).then(function(paths) {
    res.send('Files Deleted! \n ' + paths.join('\n'));
  });
});

**Comment by thammarith** [comment]
In my case, it turned out that I haven't created the folder `uploads/`.

If you encounter this, try `console.log(path)` and make sure that you have that directory created.

```javascript
const file = req.files.file
const fileName = req.files.file.name
const path = 'uploads/' + fileName

file.mv(path, function(err) {
  if (err) return res.status(500).send(err);
  res.send('File uploaded!');
});
```
