### ISSUE TITLE
when using useTempFiles: true, setting, cleanup is not exeuted after fileupload is completed.

### ISSUE THREAD

**Issue by Romkin7** [richardgirges/express-fileupload#335]
https://github.com/richardgirges/express-fileupload/blob/4f81fc822d385e3e404a3266a76c103f543c3a2a/lib/tempFileHandler.js#L53

**Comment by elliotsayes** [comment]
Yes and the `FileArray` does not support iterating through the files to clean them up yourself!

So `useTempFiles: true` is completely unusable in production without leaking disk space to unexpected file keys 🤡

Could someone e.g. @richardgirges please look at this?

**Comment by lamberto15** [comment]
for now just add a trycatch with finally, then add the logic here to clean if tmp/upload has file, dont forget to add logic or else other user that has been upload concurrent will also deleted.

**Comment by RomanBurunkov** [comment]
> https://github.com/richardgirges/express-fileupload/blob/4f81fc822d385e3e404a3266a76c103f543c3a2a/lib/tempFileHandler.js#L53

Why it should be executed after upload completion?
This function should be executed in case of errors or abortions.

then it is up to the application how to use temporary files.

**Comment by RomanBurunkov** [comment]
> Yes and the `FileArray` does not support iterating through the files to clean them up yourself!
> 
> So `useTempFiles: true` is completely unusable in production without leaking disk space to unexpected file keys 🤡
> 
> Could someone e.g. @richardgirges please look at this?

For what?
You got date with uploaded files, then it is time to work with them by your own.
Middleware just do what it should: uploads files and provides them through request object for further processing.

**Comment by RomanBurunkov** [comment]
Closing, since cleaning up successfully uploaded files is a responsibility of the app, not a middleware.
