### ISSUE TITLE
"errno":-4058,"code":"ENOENT","syscall":"open"

### ISSUE THREAD

**Issue by bharathbk18** [richardgirges/express-fileupload#338]
https://www.geeksforgeeks.org/file-uploading-in-node-js/?tab=article

i have tried as in the above website but i am facing the following  error {"errno":-4058,"code":"ENOENT","syscall":"open","path":"D:\\Backup -4-\\Task Maintenance\\Task Maintenance\\uploads\\mypic-1669011651899.jpg","storageErrors":[]}

**Comment by hassonor** [comment]
In this link The use multer package bro

**Comment by hassonor** [comment]
> https://www.geeksforgeeks.org/file-uploading-in-node-js/?tab=article
> 
> i have tried as in the above website but i am facing the following error {"errno":-4058,"code":"ENOENT","syscall":"open","path":"D:\Backup -4-\Task Maintenance\Task Maintenance\uploads\mypic-1669011651899.jpg","storageErrors":[]}

In this link The use multer package bro

**Comment by HatimHJ** [comment]
use the full link in the form action `http://localhost:${PORT}/` instead of '/'

**Comment by RomanBurunkov** [comment]
Closing this since it is old issue that is not related to the express-fileupload.
