### ISSUE TITLE
Adding an additional property to files! 

### ISSUE THREAD

**Issue by jashanbhullar** [richardgirges/express-fileupload#34]
Working on uploading a a complete folder to the server. Need webkitRelativePath property of the file to preserver directory structure. Please add this functionality or point me in the right direction, i will do it myself.

**Comment by richardgirges** [comment]
Hey @jashanbhullar I'm not quite sure I understand the request. Can you elaborate?

All of the source code is in the `lib/index.js` file:
https://github.com/richardgirges/express-fileupload/blob/master/lib/index.js

Feel free to send a PR!

**Comment by jashanbhullar** [comment]
Let's say i upload a complete directory from a client's system using a simple HTML form, then i want to replicate the directory structure under that directory on the server. There's no option for me to do that in this module.
See [multer](https://www.npmjs.com/package/multer) 's `preservepath` and `originalname`

**Comment by RomanBurunkov** [comment]
Closing that since no updates here for a while.
