### ISSUE TITLE
Image not moving to server folder

### ISSUE THREAD

**Issue by okeze-stephen** [richardgirges/express-fileupload#340]
I have tried many times design an application for uploading and saving images on database but the each time i tried, the image file is not moving to the server directory.
please i need help on how to resolve it.

This is my index.js for my node and Express Backend
const express = require('express');
const uploadedFile = require('express-fileupload');
const cors = require('cors');

const app = express();
const port = process.env.PORT || 5000;

app.use(express.json());
app.use(cors());
app.use(uploadedFile());

// Upload Endpoint Request
app.post('/upload', (req, res) => {
    if(req.files === null) {
        return res.status(400).json({ msg: 'No file to upload'});
        
    }
    // name of the input image
    const file = req.files.file;
    const filePath = __dirname + '/uploads/'+file.name;
    // console.log(file);

    // use mv() to place the file on the server
    file.mv(filePath, function(err) {
        if(err) return res.status(500).send(err);

        res.send('File Uploaded Successfully');

    });

/*
    file.mv(`${__dirname}/client/public/uploads/${file.name}`, err => {
        if(err) {
            console.error(err);
            return res.status(500).send(err);
        }

        res.json({ fileName: file.name, filePath: `/uploads/${file.name}` });
    });

    */

});

app.listen(port, ()=> console.log(`Server Running on PORT:${port}`));

Here is my code for react frontend

import React from 'react';
import '../styles/admin_styles/bootstrap.min.css';
import '../styles/admin_styles/responsive.css';
import '../styles/admin_styles/bootstrap-select.css';
import '../styles/admin_styles/perfect-scrollbar.css';
import '../styles/main.css';
import '../styles/styles.css';
import {Row, Col, Form, Button } from 'react-bootstrap';
import { link, useNavigate  } from 'react-router-dom';
import { useState, useEffect } from 'react';
import axios from 'axios';

const AddProducts = () => {
    
    //let history = useNavigate();    // use for Navigation on Previous

    const [data, setData]=useState({
        // productName: "",
        // productType: "",
        // manufacturer: "",
        // productPrice: "",
        // description: "",
        selectedFile: "",
        selectedFilePreview: null,
        fileUploaded: {},
    })

    const handleChange=(e)=>{
        setData({ ...data, 
            // productName: e.target.value,
            // productType: e.target.value,
            // manufacturer: e.target.value,
            // productPrice: e.target.value,
            // description: e.target.value,
            selectedFile: e.target.files[0],
            selectedFilePreview: URL.createObjectURL(e.target.files[0]),
            
        });

    }

    const submitForm = async (events) =>{
        events.preventDefault();
        const formdata = new FormData();
        // formdata.append('productName', data.productName);
        // formdata.append('productType', data.productType);
        // formdata.append('manufacturer', data.manufacturer);
        // formdata.append('productPrice', data.productPrice);
        // formdata.append('description', data.description);
        formdata.append('product_img', data.selectedFile);

        try {
            const res = await axios.post("http://localhost:8080/productupload",formdata, {
                headers: {
                    "Content-Type": "multipart/form-data"
                }
            });

            const { fileName, filePath } = res.data;

            setData({...data, 
                fileUploaded: { fileName, filePath }
                });

        } catch (err) {
            if (err.response.status === 500) {
                console.log(err.response.me);
                // console.log("There was a problem with the server");
            } else {
                console.log(err.response.data.msg);
            }
        }

        // to post to database 

        // if (data.selectedFile != "") {    
        //     console.log(data.selectedFile);
        // }else{
        //     alert("Choose a file to upload");
        // }

    };

  return (
    <div>
        <div className="inner_page login">
        <div class="full_container">
         <div class="container">
            <div class="center verticle_center full_height">
               <div class="login_section">
                  <div class="logo_login">
                     <div class="center">
                        <img width="210"  src="assets/images/logo.png" alt="#" />
                     </div>
                  </div>
                <div className="login_container">
                <div className="container-fluid" >
                    <span className="top-text2" > Add New Products </span>
                </div>
                 <div class="login_form">
                <Form className='Login-form' controlId="formBasicFname" method='POST' encType='multipart/form-data'>
                <div className="prct_img">
                    <Form.Group className="mb-3">
                         { data.selectedFilePreview !== null ?
                         <img name="productimgDisplay" src={data.selectedFilePreview} width="150" height="150" />
                        : <img name="productimgDisplay" src="assets/images/products_images/product_img.jpg" width="150" height="150" />	}
                        <Form.Control required type='file' name="product_img" accept="image/*" onChange={handleChange} style={{background: "#ff5722", color: "#fff"}} />
                    </Form.Group>
                </div>

{/*
                    <Form.Group className="mb-3" controlId="formBasicProductname">
                        <Form.Control required type='text' name="productName" placeholder="Enter Product Name" />
                        <Form.Text className="text-muted">
                        </Form.Text>
                    </Form.Group>

                    <Form.Group className="mb-3" controlId="formProductType">
                        <select name="productType" class="form-control">
                            <option value="" selected>Select Product Type</option>
                            <option value="Married">Fanta</option>
                            <option value="Single">Merinda</option>
                        </select>
                    </Form.Group>

                    
                    <Form.Group className="mb-3" controlId="formManufacturer">
                        <select name="manufacturer" class="form-control">
                            <option value="" selected> Select Manufacturer</option>
                            <option value="Coca-Cola">Coca-Cola</option>
                            <option value="7up">7up Bottling Company</option>
                            <option value="Guinness">Guinness</option>
                            <option value="Intafact">Intafact</option>
                            <option value="Aqua">Aqua Rapha</option>
                            <option value="NBC">NBC</option>
                            <option value="NBL">NBL</option>
                        </select>
                     </Form.Group>

                    <Form.Group className="mb-3" controlId="formBasicPrice">
                        <Form.Control required type='text' name="productPrice" placeholder="Enter Price..." />
                        <Form.Text className="text-muted">
                        </Form.Text>
                    </Form.Group>
                    
                    <Form.Group className="mb-3" controlId="formBasicDescription">
                        <Form.Control required type='text' name="description" placeholder="Enter the Description of the product here...." />
                        <Form.Text className="text-muted">
                        </Form.Text>
                    </Form.Group>

*/}

                    <Button onClick={submitForm} type='submit' name='submit' variant="primary" style={{width: "40%", marginRight: "5px", background: "#39CDCC", borderColor: "#39CDCC", color: "#fff"}} >
                        Submit
                    </Button>

                <Button href='#' type='cancel' name='exit' style={{width: "40%", marginLeft: "5px", background: "#d34836", borderColor: "#d34836", color: "#fff"}} >
                    Exit
                </Button>
                    
                </Form>
             </div>
                </div>
               </div>
            </div>
         </div>
      </div>
        </div>

    </div>
  )
}

export default AddProducts;

**Comment by bhumit070** [comment]
Hello there 
you are appending image as product_img from the frontend and accessing as req.files.file in backend 
so it will be undefined and it will throw an error while using it please fix it and it might work as expected

and if it fixes it please close the issue
