### ISSUE TITLE
How to upload through api instead of from form?

### ISSUE THREAD

**Issue by zhouhao27** [richardgirges/express-fileupload#35]
I'm wondering if it's possible to uplad multiple files (or data) through api instead of through form? Any example? Thanks.

**Comment by richardgirges** [comment]
Hey @zhouhao27 it sure is.

Here is an example of the `superagent` package uploading an array of files:

https://github.com/richardgirges/express-fileupload/blob/master/test/multipartUploads.spec.js#L138

There are other examples in the unit tests as well.
