### ISSUE TITLE
Does the file upload work for react native apps ?

### ISSUE THREAD

**Issue by varshith5c** [richardgirges/express-fileupload#350]
I have setup all the configuration correctly. When I hit the API using web browser I am able to upload the file . ie I am able to get `req.files` but when I send it from mobile eventhough the header is multipart/form-data I am not able to get any data in `req.files`. I always get null as a value

**Comment by RomanBurunkov** [comment]
Hi.

What exact header you had?
Any examples, snippet, configuration details?

**Comment by king-d-dev** [comment]
You need to install [form-data](https://www.npmjs.com/package/form-data) and then do this
const formData = new FormData()

**Comment by RomanBurunkov** [comment]
No answers from the issue author
