### ISSUE TITLE
express-fileupload may need to update the version of dependency busboy

### ISSUE THREAD

**Issue by yitcai** [richardgirges/express-fileupload#352]
per https://github.com/expressjs/multer/issues/224, busboy fixed a issue in latest version. But I am still getting exactly the same error when using express-fileupload. So I guess express-fileupload  hasn't;t updated the version of dependency package busboy. Can you please check and update if this is correct? Thank you very much!

**Comment by RomanBurunkov** [comment]
Hi.
The latest express-fileupload 1.4 has "busboy": "^1.6.0", which is the latest version according to the npm.
