### ISSUE TITLE
Using a useTempFiles: true results in a empty buffer

### ISSUE THREAD

**Issue by shreekrishnalamichhane** [richardgirges/express-fileupload#354]
# My environment

express: `^4.18.2`
express-fileupload: `^1.4.0`
node: `v18.17.0`
os: `Ubuntu 23.04`
-=================================

# Issue
When `useTempFiles: false`, file buffer has data.
![image](https://github.com/richardgirges/express-fileupload/assets/47468714/6c753004-4d18-4948-ab06-b4f372e6bc29)

When `useTempFiles: true`, file buffer has no content and buffer size is 0.
![image](https://github.com/richardgirges/express-fileupload/assets/47468714/774b3f01-111b-4c52-8ab1-b82cc480716f)

-=================================

My middleware config

```js 
app.use(
  fileUpload({
    useTempFiles: true,
    tempFileDir: './tmp/',
    abortOnLimit: true,
    limits: { fileSize: 50 * 1024 * 1024, files: 1 },
    responseOnLimit: 'File size limit has been reached',
    uploadTimeout: 10000, // 10 seconds
  })
);
```

My controller code

```js
check: async (req: Request, res: Response): ExpressResponse => {
    try {
      const file = req.files?.file as UploadedFile | null | undefined;

      if (!file) throw new CustomError('File not found', 400);

      console.log(file);
      console.log('Buffer Length:', file.data.length);

    } catch (error) {
      console.log(error);
    }
}
```

**Comment by RomanBurunkov** [comment]
Hi,

This is why useTempFiles options had been created: to not store uploads in the memory.
So it works as designed.
