### ISSUE TITLE
.mv creates 0byte empty file

### ISSUE THREAD

**Issue by mission10138** [richardgirges/express-fileupload#39]
i got this to create files in my uploads directory but it isnt putting anything in the file. os.tmpdir says my temp dir is /tmp/ but there arent any uploads in there either.

**Comment by r3wt** [comment]
@mission10138 have you tried using the `tmp` module?

the following works for me on both linux and windows:

```js
//write incoming file to temp files similar to php
app.use(function(req,res,next){
	if(req.files){
		var work = [];
		for(var prop in req.files){
			var file = req.files[prop];
			if(file.name==''){
				delete req.files[prop];
			}else{
				tmp.file(function(err, path, fd, cleanupCallback) {
					req.files[prop].mv(path, function(err) {
						req.files[prop].clean = cleanupCallback;
						req.files[prop].path = path;
						next();
					});
				});
			}
		}
	}else{
		next();
	}
});
```

**Comment by richardgirges** [comment]
Hey @mission10138 can you send me some more details regarding what OS and version of the OS you're using? Node version, and version of express-fileupload as well if possible. Will try to reproduce this after I can get some more details. Thanks!

**Comment by richardgirges** [comment]
Closing this out due to inactivity, but please re-open if you are still experiencing this on the latest version of express-fileupload

**Comment by samuelguesnier** [comment]
same issue. Ubuntu 18.04.1 LTS 64 bits
node 8.7.0 
 express file upload 1.1.1-alpha.2

code: 
```
app.use(fileUpload());


router.get('/', function(req, res, next) {
  res.render('index', { title: 'Prototype' });
});

router.post('/file', function(req, res) {
  req.files.fichier_excel.mv('fichier2.csv', function(err) {
    if (err)
      return res.status(500).send(err);
    else
      console.log("sucess")

    
  });
```

**Comment by RomanBurunkov** [comment]
Hi, you should try the latest version 1.1.1-alpha.3

**Comment by samuelguesnier** [comment]
Thanks it works now
