### ISSUE TITLE
limit fileSize

### ISSUE THREAD

**Issue by secofeixo** [richardgirges/express-fileupload#40]
I'm not able to detect when a file has reached the limit specified by the options when the fileupload object is created.
The module runs the next() but without any message that the file have reached the max fileSize but the file is saved truncated.
Maybe a new field truncated can be added to req.file, indicating that the file has been truncated and it has exceeded the maxFileSIze.

**Comment by richardgirges** [comment]
This is a really good catch. I'll look into it. Thanks!
