### ISSUE TITLE
limit file size per action not whole app

### ISSUE THREAD

**Issue by prtome** [richardgirges/express-fileupload#41]
Hello, 
is there a way to limit /check the file size per route call? I have various places in my application where I upload files, and the size limit is different for each of them I do it in the client, but want to double-check in the server. Is there a way I can check the file size in the route call so I do what I need to do ?
Thanks

**Comment by richardgirges** [comment]
There is no way to do that with this library unfortunately. Happy to take a PR if you can think of a clean and minimalistic API for how this would work :)

**Comment by prtome** [comment]
Thanks.
Next is certainly a dumb question. I am looking at the size of the buffer: req.files.data.size
 which seems to give me the size of my file  - right ?
Then I can simply in each route check the size and load or not the file in the db. 
Does this make sense ?

**Comment by RomanBurunkov** [comment]
Closing that since suitable workaround has been proposed and there are no updates for a long time.
