### ISSUE TITLE
My file is not `.mv` move to folder

### ISSUE THREAD

**Issue by erevos-13** [richardgirges/express-fileupload#43]
Hello very nice work, i have a an issue.
I upload the file i see the file object in my `console.log(req.files.filetoupload);`
but the when i move the file:
```
req.files.filetoupload.mv(__dirname + 'upload',function (err) {
        if(err) throw err;
    });
```
i do not have an  err but still the file is not load.
i have sudo permisions

**Comment by r3wt** [comment]
To any future readers, please *RTFM*

**Comment by gosongs** [comment]
RTFM means 'Read The Fucking Manual'
