### ISSUE TITLE
mv function error

### ISSUE THREAD

**Issue by qaz40520** [richardgirges/express-fileupload#44]
when I upload image, return this error
`{
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "public/images/visitor7.jpg"
}`
please help me ~~

**Comment by gosongs** [comment]
@qaz40520 hi, man, How did you solve the problem?

**Comment by hoangdangal** [comment]
I got this error , how to fix it ? please help and thank.
