### ISSUE TITLE
Way to get path of the file?

### ISSUE THREAD

**Issue by ezetojo** [richardgirges/express-fileupload#45]
Im using express-fileupload to get the file from the client side form but i need to use ftp to move it so i need the path, is there any way to do it using this?

**Comment by Naktibalda** [comment]
@ezetojo `express-fileupload` keeps uploaded file in memory, use `mv` method for writing uploaded file to filesystem.

**Comment by ezetojo** [comment]
@Naktibalda ohhh i get it now. I can move the uploaded file to a temp path and then use ftp. Thank you!

**Comment by Nasirkhan-259** [comment]
Well there should be a temp path as i wanted to skip that part to upload to a tmp path and then process :(

**Comment by richardgirges** [comment]
@Nasirkhan-259 there's an open PR #88 which provides you with the option to upload directly to a tmp path on the filesystem. The PR has conflicts though - happy to take a different PR if someone is willing to build out this functionality.
