### ISSUE TITLE
Create md5 checksum on data

### ISSUE THREAD

**Issue by khessels** [richardgirges/express-fileupload#48]
It might be an idea to create an md5 property.
Many uses really, but for me to ulpoad a file and have the md5 ready saves a few steps.

**Comment by richardgirges** [comment]
Sounds like a good idea. I'm listing this as an enhancement and will try to look into it for the next minor version rollout. If you are willing to consider sending a PR in the meantime, it would be much appreciated!

**Comment by richardgirges** [comment]
@Shudrum thanks!
