### ISSUE TITLE
Using with superagent and react

### ISSUE THREAD

**Issue by PaulRosset** [richardgirges/express-fileupload#49]
I would like to upload a image file on my server with superagent and react.
But my ```req.files```is always undefined.

I will appreciate if someone can help me on it :)

Here is my code : 
``` 
const fileUpload = require('express-fileupload');
app.use(fileUpload())
```
Server side:
```const fileUpload = require('express-fileupload');app.use(fileUpload())
app.post('/uploadprofile', (req, res) => {
        console.log(req.file);
        console.log(req.files);
        console.log(req.body);
        res.status(200).end()
})
```

Client:
```
onUploadFile(e) {
        console.log(e.target.files[0])
        this.setState({
            img: e.target.files[0]
        }, () => {
            agent
            .post("http://localhost:3100/uploadprofile")
            .attach('profil', this.state.img, this.state.img.name)
            .set("Content-Type", "")
            .end((err, res) => {
                console.log(err)
                console.log(res)
                console.log("send")
         })
        })
    }

render() {
   return (
        <input id="file" type="file" accept="image/*" name="profil" className="inputButton" 
        onChange={this.onUploadFile}/>
     )
}
```

In my superagent request, I have to overwrite the content-type, otherwise json data are send.

But the req.file is still undefined on my backend.

Thanks for the help !

**Comment by richardgirges** [comment]
Your server configuration looks correct. However, express-fileupload won't work if you set the `Content-Type` to an empty string - I also don't think that's generally a good practice. What is the issue that led you to setting the Content-Type this way?

**Comment by PaulRosset** [comment]
Thanks for the reply, 

Because I need to pass only the content-type ```form-data``` but some json data are also sent. I can't send both. So, if I don't do this , it will result with an error cause of the json.

**Comment by PaulRosset** [comment]
Ok, thanks for the help, I found the solution, it's because I was declaring bodyParser middleware on my whole application and he was overwritting the fileUpload middleware.
Now I declare bodyParser on each specific route and everythings works fine.

**Comment by richardgirges** [comment]
Great, glad you found it!
