### ISSUE TITLE
Tmp file?

### ISSUE THREAD

**Issue by antoinerousseau** [richardgirges/express-fileupload#52]
I was wondering, if I don't use `mv()`, what happens to the file? Does it stay in a temporary folder?

**Comment by tumulr** [comment]
As per my knowledge, all the data of the file is present in req.files(in-memory) and since you haven't moved it to a location using the mv function it should remain in-memory.

@richardgirges Correct me if I am wrong?

**Comment by antoinerousseau** [comment]
if it's not initially on the disk, I think the method should be named more like `.save()` or `.saveTo()`

**Comment by richardgirges** [comment]
@tumulr that is correct. @antoinerousseau that's a good point. I can't eliminate the `.mv` function without putting it through a deprecation phase as it would be a pretty major breaking change. But I would be open to a PR that introduces a method named `.save()` that aliases `.mv()` for the time being.

Closing this out as it's not an actual issue. Lemme know if you'd be interested in making a PR for this.
