### ISSUE TITLE
Uploaded file URL

### ISSUE THREAD

**Issue by Felonius-Gru** [richardgirges/express-fileupload#53]
Hello, Thanks for your simple file upload package!
I want to upload file and get URL of uploaded file as response.
Is there anyway to get this?
Thanks.

**Comment by richardgirges** [comment]
@Felonius-Gru thanks :)

You will have to build the URL of the uploaded file yourself, as it wouldn't be possible for express-fileupload to know the proper URL.

For example:
* Your website's url is `http://www.foo.com`
* You upload a file with express-fileupload
* You use express-fileupload's `.mv()` function to move the file into your `/images` directory
* You can now access the file from `http://www.foo.com/images/FILENAME.JPG`

Hope this helps !
