### ISSUE TITLE
mv not returning error with missing source file

### ISSUE THREAD

**Issue by ohelli** [richardgirges/express-fileupload#55]
Hello,
i am currently debugging an issue in an express app using fileupload. In this issue, a user uploads a file but accidentally moves the source file to another directory before uploading it - meaning the file shouldn't be found and the `mv` method should return an error. 
This is happening in Firefox and Chrome, however not in Safari. Can you think of a reason for this?
Thank you for your help.

My setup is: 
* node: v7.6.0
* express: "^4.14.0"
 * express-fileupload: "0.0.5"

The code using `mv` is the following:
```javascript
	uploadedMedia.mv(absolute_path, function(err){
		if (err) {
            res.status(400).send({result:false, error:err});
        }else{
        	res.status(200).send({result:true});
        	if(extension == 'wav'){
        		var mp3_path = absolute_path.slice(0, -3) + "mp3";

        		var command = 'lame ' + absolute_path + " " + mp3_path + " && rm " + absolute_path;
        		cmd.run(command);
        		console.log(command);
        	}
        }
	});
```

**Comment by ohelli** [comment]
If it helps, the `mv` method creates an empty target file at the given `absolute_path`.

**Comment by richardgirges** [comment]
@ohelli  this is definitely a bug. We will need to confirm that a file exists (i.e. the file's data.length > 0) and then return an error if `.mv()` is executed. 

Any PR to address this would be greatly appreciated, otherwise, I will look into this soon.

Cheers

**Comment by ohelli** [comment]
Thanks for this. Don't have time to do it myself a the moment. I will recommend using Chrome and Firefox as a workaround until its fixed.

**Comment by richardgirges** [comment]
Closing as I believe this is fixed on the latest version.
