### ISSUE TITLE
not recognizing empty files

### ISSUE THREAD

**Issue by patroclos** [richardgirges/express-fileupload#56]
When I try to upload an empty file, I get nothing in request.files

**Comment by tumulr** [comment]
@richardgirges I checked the code and found that if there is no data no object is getting created in req.files(Line 93 in index.js). 

How do you want to handle it? I can help if you want.

**Comment by richardgirges** [comment]
@tumulr it sounds like we can simply create an empty object in req.files in the event that this happens. Curious how other systems do it, like multer.

**Comment by richardgirges** [comment]
Closing as this issue has gone stale and I believe it's resolved now.
