### ISSUE TITLE
Crashes when the multipart request is empty. And crashes the node instance.

### ISSUE THREAD

**Issue by mbisono** [richardgirges/express-fileupload#6]
Can be replicated by launching a rest client like Advanced REST client and trying to upload a file without selecting one.

6:57:30 PM web.1 |  events.js:85
6:57:30 PM web.1 |        throw er; // Unhandled 'error' event
6:57:30 PM web.1 |              ^
6:57:30 PM web.1 |  Error: Unexpected end of multipart data
6:57:30 PM web.1 |      at /Users/xxxxxx/Documents/workspace2/node-tickets/node_modules/dicer/lib/Dicer.js:62:28
6:57:30 PM web.1 |      at process._tickCallback (node.js:355:11)

**Comment by richardgirges** [comment]
@mbisono I'm trying to reproduce - can you show me your express request handler code?

**Comment by mbisono** [comment]
Hi,
I'm no longer using express-fileupload since I switched to using amazon s3, but I pulled the old code from the git history:

this was my route handler definition:

router.post('/', expressFileupload(), require('./set-logo'));

I think it crashed before entering the 'set-logo' handler. Hard to tell since it's been a while.

I only used it for a couple of days.

**Comment by pat310** [comment]
I'm having a similar problem when using multipart with `express-fileupload`.  You can try [this example](https://github.com/expressjs/multer/issues/224) posted on `multer`.
