### ISSUE TITLE
support Node.js 6.11.1

### ISSUE THREAD

**Issue by himadrinath** [richardgirges/express-fileupload#60]
@richardgirges  does it support Node.js 6.11.1 because i am using it with google cloud functions and it support only v6.11.1........

**Comment by richardgirges** [comment]
Hi @himadrinath can you give me some more information? What specifically isn't working? Are you seeing a certain error?

Also, what version of express-fileupload are you using? 

Thanks!

**Comment by himadrinath** [comment]
@richardgirges  i found out the problem
https://stackoverflow.com/questions/47242340/how-to-upload-a-file-using-express-on-firebase-cloud-functions
