### ISSUE TITLE
Setting max file size

### ISSUE THREAD

**Issue by sahasd** [richardgirges/express-fileupload#7]
How do I modify the file size for the files coming in?

**Comment by richardgirges** [comment]
You can modify the file size the same way that you can in busboy. Busboy options can be passed into the `fileUpload()` middleware like so:

```javascript
app.use(fileUpload({
	limits: { fileSize: 50 * 1024 * 1024 },
}));
```

**Comment by jamesjoel** [comment]
how i get file size in fileUpload()
