### ISSUE TITLE
How to write to root folders ?

### ISSUE THREAD

**Issue by chanakaDe** [richardgirges/express-fileupload#76]
Hi,
/opt/lampp/htdocs/upload/
This is the folder of my local LAMPP. 
I want to write files to this.
But there's a permission issue i think.
how to fix please ?

**Comment by richardgirges** [comment]
Hey @chanakaDe, unfortunately this is an issue that's local to your workstation. I'm not familiar with LAMPP so I'm not sure how you can enable permissions on different folders. My guess is that you're going to have to Apache Directory Permissions. 

This post might help, but I'm not too sure: https://askubuntu.com/questions/325498/apache-cant-access-folders-in-my-home-directory?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
