### ISSUE TITLE
Cannot read property 'mv' of undefined

### ISSUE THREAD

**Issue by samgitre** [richardgirges/express-fileupload#8]
Please what is the meaning of the mv in sampleFile,mv() and where does it come from? this is the error message I got when I run it:  (Cannot read property 'mv' of undefined)

**Comment by lfarroco** [comment]
Had this issue as well while using the single file upload. Instead of looking for the files array, I switched to `req.files.file`.

**Comment by richardgirges** [comment]
@samgitre `req.files` is an object, not a property. 

So if you upload a file with the field name "myFile", you can access it with `req.files.myFile`, at which point you can execute `req.files.myFile.mv()`

**Comment by utkarsharma2** [comment]
Hi,

What mv is intended to do?

**Comment by jonas060831** [comment]
@richardgirges  'var imagedata = req.files.imageinput.data;' 

i tried to get the buffer using this but it gives me
Cannot read property 'imageinput' of undefined when i tried to deploy it on serverless... locally it works but when deploying to serverless it doesnt please help
