### ISSUE TITLE
Serverless: Error: Unexpected end of multipart data

### ISSUE THREAD

**Issue by jonas060831** [richardgirges/express-fileupload#80]
Tried to use express-upload together with serverless
after deploying to aws and trying the endpoint it gives me error 500

when running the code with node locally it works fine 

i also did tried to run the endpoint locally with serverless offline and it gives me

**Error: Unexpected end of multipart data**
and 

**Cannot read property 'imageinput'** 

this is the route 

```

// express fileupload size
app.use(fileUpload({
  //turn on the limit
  abortOnLimit: true,
  //13.10MB
  limits: { fileSize: 100 * 1024 * 1024 },

}));

app.post('/upload-image', function(req, res){

  if (!req.files){
     res.status(400).send('No files were uploaded.');
  }

    // The name of the input field (i.e. "sampleFile") is used to retrieve the uploaded file
    const imagedata = req.files.imageinput.data

    gm(imagedata)
    .resize(425, 300)
    .toBuffer((err, buffer) => {

      if (err) {
        console.log(err);
      }

      //deleting the original name and putting each character between period
      var filename =  req.files.imageinput.name.split(".");
      //a combination of uniqueString plus unixTimeStamp plus another uniqueString
      //getting the last period of the file type to lower case this will be the new filename pop the .fileExt from the name
      var newfilename = uniqueString() + '~'+ unixTime(new Date()) + '~'+ uniqueString() + '.' + filename.pop().toLowerCase();

      s3.putObject(buffer, "amazonurl", newfilename)
      //hardcode value
      res.send('amazonurl'+ newfilename);
    })

});
```

**Comment by richardgirges** [comment]
@jonas060831 would I be able to trouble you for a demo codebase with this issue replicated? My guess is that there's a problem with another middleware that is clashing with express-fileupload.

**Comment by RomanBurunkov** [comment]
The error: 
  Error: Unexpected end of multipart data

is throwing by busboy, it looks that something wrong with a data comming to it.

As a result you got the next one: Cannot read property 'imageinput', because express-fileupload hadn't add it to the files object.

@jonas060831 if this issue still actual probably you should to create an issue with busboy.

**Comment by RomanBurunkov** [comment]
Some cooments about it from stackjoverflow:

> For me, I received this error when I used \n newlines instead of \r\n newlines when formatting my post body on the client side.
> 
> When I fixed the newlines (as seen in code below) it worked.

**Comment by RomanBurunkov** [comment]
Closing since it doesn't look like this middleware issue and probably this is no longer relevant.
