### ISSUE TITLE
Clarification needed : Why is this done as a middleware?

### ISSUE THREAD

**Issue by orshee** [richardgirges/express-fileupload#82]
I'm just curious, why have you decided to create this module as middleware ?
Access to req object, or dynamic binding to form elements, or something else?

Thanks in advance

**Comment by richardgirges** [comment]
Access to the req object, in an attempt to stay consistent with express's request parameters (i.e. `req.body`, `req.query`, etc). Also, middlewares seem to be the most idiomatic approach considering most other express file upload handlers use them as well. Hope this answers your question!
