### ISSUE TITLE
Busboy fileSize limit not being applied?

### ISSUE THREAD

**Issue by Renari** [richardgirges/express-fileupload#84]
According to the docs to limit the file size I would do the following.

```js
app.use(fileUpload({
  limits: {
    fileSize: 20 * 1024 * 1024, // 20MB
  },
  abortOnLimit: true,
}));
```

However when doing this when I upload a 60MB I'm not getting a 413 response, rather everything proceeds as if the `fileSize` limit doesn't exist.

**Comment by MrToph** [comment]
Same issue here, could you figure out a solution or why did you close this? @Renari

**Comment by Renari** [comment]
I don't recall, sorry. I don't even remember which project I used this for.

**Comment by RayPS** [comment]
I had the same issue: the request is stuck until client timeout but not being ended with 413 while over size limit.

**Comment by RayPS** [comment]
@Renari Could you re-open this for us.

**Comment by mayurpunjabi** [comment]
I am having the same issue here, file upload proceeds normally even if file size is bigger than the limit

**Comment by richardgirges** [comment]
Hello, can y'all share any information about your deployment setup? It's possible that if you have a load balancer, proxy, or web server routing to your express server, that the 413 error is not actually coming from the express server. This would explain why you are seeing a 413 error despite having the correct configuration for file size limits in express.

I'm going to close this issue but I will reopen it when you can share more information on your deployment setup.
