### ISSUE TITLE
Multiple upload

### ISSUE THREAD

**Issue by tymiao1220** [richardgirges/express-fileupload#85]
Is there a way to handle multiple files coming from one input` <input type='file' name='abc' multiple> `
instead of separate them into several `<input>`s? 

When I do that, `req.files` return `null`
Thank you in advance!

**Comment by richardgirges** [comment]
Hey there, can you provide me some example code? It would make it much easier to figure out whether or not express-fileupload can do anything differently to support the `multiple` attribute within the `<input>` tag.

Thanks!

**Comment by Kakakirbz** [comment]
Here are screenshots of my code.

![image](https://user-images.githubusercontent.com/22406521/45582462-e346fc80-b8e2-11e8-8bc7-a32eb5c919b8.png)
![image](https://user-images.githubusercontent.com/22406521/45582464-e6da8380-b8e2-11e8-950e-1d334e472b3e.png)
![image](https://user-images.githubusercontent.com/22406521/45582465-f22daf00-b8e2-11e8-8cfc-10b884b4dd3e.png)

**Comment by richardgirges** [comment]
Thanks @Kakakirbz. @tymiao1220 closing this out. Please let us know if you still require assistance.

**Comment by scheng123** [comment]
Hold on, does uploading multiple files turn the req.files.FILENAME into an array?

**Comment by scheng123** [comment]
So I can handle the array and I'll be find and dandy right?
