### ISSUE TITLE
Encoding type for the buffer representation of the buffer

### ISSUE THREAD

**Issue by louloup22** [richardgirges/express-fileupload#90]
Hello, I am trying to upload a word document (.docx) using express-fileupload. This seems to be working but when I'm trying to decode the buffer (I am using Python for that sending the buffer array) it seems I am not using the right decoding (I am trying 'utf-8'). How can I decode properly the buffer and retrieve the text from my document ?

**Comment by RomanBurunkov** [comment]
Hi @louloup22 , 

Issue description is quite vague, please ellaborate it.

**Comment by RomanBurunkov** [comment]
Closing, since this is no longer relevant.

**Comment by kevinsingapore** [comment]
and how to get req.files.name display charset:utf-8 through express-uploadfiles?

**Comment by kevinsingapore** [comment]
> Hello, I am trying to upload a word document (.docx) using express-fileupload. This seems to be working but when I'm trying to decode the buffer (I am using Python for that sending the buffer array) it seems I am not using the right decoding (I am trying 'utf-8'). How can I decode properly the buffer and retrieve the text from my document ?

finally, did u solved thie issue?
