### ISSUE TITLE
mv() is not a function

### ISSUE THREAD

**Issue by snehap007** [richardgirges/express-fileupload#94]
we are using express-fileupload npm packge (https://www.npmjs.com/package/express-fileupload)
while uploading file we are facing error of mv() is not a function in below code 
` app.post('/upload', function(req, res) {`
  `if (!req.files)`
    `return res.status(400).send('No files were uploaded.');`
    ` let sampleFile = req.files.sampleFile;`
    `// Use the mv() method to place the file somewhere on your server`
    `sampleFile.mv('/somewhere/on/your/server/filename.jpg', function(err) {`
    `if (err)`
      `return res.status(500).send(err);`
   ` res.send('File uploaded!');`
  `});`

please help me in this.

**Comment by richardgirges** [comment]
@snehap007 most likely you are not calling your uploaded file's form field `sampleFile`. Can you show us an example of your frontend code?

Thanks

**Comment by daaashley** [comment]
@richardgirges I'm having this problem too, but .mv works when I load the page in Chrome but doesn't work when I load it in Internet Explorer or Edge. This makes me think it has something to do with the way the package works with these browsers. Any advice?

**Comment by richardgirges** [comment]
@daaashley this is a backend package that runs in Node.js. So it's highly unlikely that the browser has any bearing on the way this package works. I would advise you to check out your frontend file upload code for any browser compatibility issues. Please re-open an issue if you discover a problem with express-fileupload :)
