### ISSUE TITLE
Uploading more than 5-10 files causes hanging of express app untill upload done

### ISSUE THREAD

**Issue by RomanBurunkov** [richardgirges/express-fileupload#97]
Hi there,

I use express-fileupload to uploading audio files(mostly mp3 tracks with size about 5-15 megabytes).

Uploading more than 5-10 files in the same time causes hanging of express app untill upload has been done.

Vesrsions:
- Node 8.12.0
- express@4.16.3
- express-fileupload@1.0.0-alpha.1

During upload in progress any requests to express stuck.

My upload code:

```
  
  router.post('/content/audio/upload', (req, res)=>{
    let token = req.query.token || req.headers['x-access-token'];
    if(!req.files || !req.files.audio_file){
      return res.status(400).send('No files were uploaded.');
    }
    storeModel.put({
      fileName : req.files.audio_file.name,
      fileData : req.files.audio_file.data,
      fileType : 'AUDIO'
    }, (err, data) => {
      if (err){
        api.logMessage(`Failed to add file ${req.files.audio_file.name} to Storage!`);
        console.error(err);
        return res.status(500).send(err);
      }
      api.logMessage(`New file ${req.files.audio_file.name} has been added to the Storage as ${data.name}.`);
      mediaModel.addAudio(data, (err, audioData)=>{
        if(err){
          api.logMessage(`Failed to add audio file ${req.files.audio_file.name}!`);
          console.error(err);
          return res.status(500).send(err);
        }
        api.logMessage(`New audio resource[${audioData.format}, ${audioData.dur} secs] ${audioData.uuid} has been added as ${audioData.name}.`);
        res.json(genOkResult(audioData));
        api.logMessage(`Sending audioAdded event...`);
        api.wsSendSubscribe({
          subscribtion   : 'audioAdded',
          excludeByToken : token
        }, {
          type : 'event',
          data : {
            id   : '',
            name : 'audioAdded',
            data : audioData
          }
        });
      });
    });
  });

```
I've added some additional logging to my code and it looks like upload middleware can block whole express app during aploading, because all operations which app makes with aplloaded data take less than second and all of them use async mysql and fs methods.

Is there any way to improve performance and avoid hanging during uploading?

Thanks Roman.

**Comment by richardgirges** [comment]
This is likely to be a system issue and not an express-fileupload issue. I ran some benchmarks and was able to get closer to 100 parallel uploads on a large virtual server. Closing this out, for now :)
